export const THEME = {
  dark: {
    bg: 'bg-[#0c0c0e]',
    text: 'text-stone-200',
    accent: 'text-indigo-400',
    glass: 'bg-stone-950/10',
    border: 'border-white/[0.06]',
    shadow: 'shadow-black/60',
    pill: 'bg-stone-900/40 border-stone-700/50',
    glow: 'from-indigo-600/30 via-purple-600/15 to-transparent',
    brand: 'text-indigo-400',
    brandBg: 'bg-indigo-500/10',
    brandBorder: 'border-indigo-500/20',
    btnPrimary: 'bg-gradient-to-br from-indigo-500 to-purple-600 text-white shadow-indigo-500/40',
    titleColor: 'text-gold',
    poetColor: 'text-gold',
    controlIcon: 'text-stone-300 hover:text-white',
    gold: 'var(--gold)',
    goldText: 'text-gold',
    goldHoverBg: 'hover:bg-gold/12',
    goldHoverBg15: 'hover:bg-gold/15',
    goldActiveBg: 'bg-gold/15',
    goldBorder: 'border-gold',
    goldBorderMuted: 'border-gold/20',
    goldBorderSubtle: 'border-gold/30',
    goldHoverBorderSubtle: 'hover:border-gold/30',
    goldBorderAccent: 'border-gold/40',
    goldBorderStrong: 'border-gold/70',
    goldHoverBorderStrong: 'hover:border-gold/70',
    goldBg10: 'bg-gold/10',
    goldBg20: 'border-gold/20',
    goldTextMuted: 'text-gold/60',
    error: 'text-red-400',
    errorBg: 'bg-red-600/80',
    debug: 'bg-black/60 border-stone-800 text-stone-300',
    debugInput: 'bg-stone-900/80 border-stone-700 text-stone-200 placeholder:text-stone-500',
    debugDivider: 'border-stone-700',
    kbd: 'bg-stone-800 text-stone-300 border-stone-700',
  },
  light: {
    bg: 'bg-[#FDFCF8]',
    text: 'text-stone-800',
    accent: 'text-indigo-600',
    glass: 'bg-white/40',
    border: 'border-white/50',
    shadow: 'shadow-indigo-100/50',
    pill: 'bg-white/40 border-white/60',
    glow: 'from-indigo-500/15 via-purple-500/10 to-transparent',
    brand: 'text-indigo-600',
    brandBg: 'bg-indigo-500/5',
    brandBorder: 'border-indigo-500/10',
    btnPrimary: 'bg-gradient-to-br from-indigo-600 to-purple-700 text-white shadow-indigo-200',
    titleColor: 'text-gold',
    poetColor: 'text-gold',
    controlIcon: 'text-indigo-950/90 hover:text-black',
    gold: 'var(--gold)',
    goldText: 'text-gold',
    goldHoverBg: 'hover:bg-gold/12',
    goldHoverBg15: 'hover:bg-gold/15',
    goldActiveBg: 'bg-gold/15',
    goldBorder: 'border-gold',
    goldBorderMuted: 'border-gold/20',
    goldBorderSubtle: 'border-gold/30',
    goldHoverBorderSubtle: 'hover:border-gold/30',
    goldBorderAccent: 'border-gold/40',
    goldBorderStrong: 'border-gold/70',
    goldHoverBorderStrong: 'hover:border-gold/70',
    goldBg10: 'bg-gold/10',
    goldBg20: 'border-gold/20',
    goldTextMuted: 'text-gold/60',
    error: 'text-red-400',
    errorBg: 'bg-red-600/80',
    debug: 'bg-white/60 border-stone-200 text-stone-700',
    debugInput: 'bg-white/80 border-stone-300 text-stone-800 placeholder:text-stone-400',
    debugDivider: 'border-stone-300',
    kbd: 'bg-stone-200 text-stone-700 border-stone-300',
  },
};

// Convenience alias: many UI elements (control bar, dropdowns, badges) always use
// the dark-mode gold regardless of current theme.  Destructuring avoids verbose
// `THEME.dark.*` references throughout the JSX.
export const GOLD = THEME.dark;
