export const THEME = {
  dark: {
    bg: 'bg-[#0c0c0e]',
    text: 'text-stone-200',
    accent: 'text-lapis-light',
    glass: 'bg-stone-950/10',
    border: 'border-white/[0.06]',
    shadow: 'shadow-black/60',
    pill: 'bg-stone-900/40 border-stone-700/50',
    glow: 'from-lapis/30 via-lapis-deep/15 to-transparent',
    brand: 'text-lapis-light',
    brandBg: 'bg-lapis/15',
    brandBgHover: 'hover:bg-lapis/15',
    brandBorder: 'border-lapis-light/30',
    btnPrimary: 'bg-lapis border border-lapis-light/40 text-white shadow-lapis/30',
    titleColor: 'text-gold',
    poetColor: 'text-gold',
    controlIcon: 'text-stone-300 hover:text-white',
    gold: 'var(--gold)',
    goldText: 'text-gold',
    goldHoverBg: 'hover:bg-gold/12',
    goldHoverBg15: 'hover:bg-gold/15',
    goldActiveBg: 'bg-gold/15',
    goldBorder: 'border-gold',
    goldBorderMuted: 'border-gold/20',
    goldBorderSubtle: 'border-gold/30',
    goldHoverBorderSubtle: 'hover:border-gold/30',
    goldBorderAccent: 'border-gold/40',
    goldBorderStrong: 'border-gold/70',
    goldHoverBorderStrong: 'hover:border-gold/70',
    goldBg10: 'bg-gold/10',
    goldBg20: 'border-gold/20',
    goldTextMuted: 'text-gold/60',
    sectionLabel: 'text-lapis-light',
    sectionBorder: 'border-lapis-light/20',
    sectionAccent: 'border-lapis-light/20',
    loadingIcon: 'text-lapis-light',
    selectionBg: 'selection:bg-lapis',
    error: 'text-red-400',
    errorBg: 'bg-red-600/80',
    debug: 'bg-black/60 border-stone-800 text-stone-300',
    debugInput: 'bg-stone-900/80 border-stone-700 text-stone-200 placeholder:text-stone-500',
    debugDivider: 'border-stone-700',
    kbd: 'bg-stone-800 text-stone-300 border-stone-700',
  },
  light: {
    bg: 'bg-[#FDFCF8]',
    text: 'text-stone-800',
    accent: 'text-lapis',
    glass: 'bg-white/40',
    border: 'border-white/50',
    shadow: 'shadow-lapis/20',
    pill: 'bg-white/40 border-white/60',
    glow: 'from-lapis/20 via-lapis-deep/10 to-transparent',
    brand: 'text-lapis',
    brandBg: 'bg-lapis/10',
    brandBgHover: 'hover:bg-lapis/10',
    brandBorder: 'border-lapis-light/20',
    btnPrimary: 'bg-lapis border border-lapis-light/40 text-white shadow-lapis/20',
    titleColor: 'text-gold',
    poetColor: 'text-gold',
    controlIcon: 'text-stone-700 hover:text-black',
    gold: 'var(--gold)',
    goldText: 'text-gold',
    goldHoverBg: 'hover:bg-gold/12',
    goldHoverBg15: 'hover:bg-gold/15',
    goldActiveBg: 'bg-gold/15',
    goldBorder: 'border-gold',
    goldBorderMuted: 'border-gold/20',
    goldBorderSubtle: 'border-gold/30',
    goldHoverBorderSubtle: 'hover:border-gold/30',
    goldBorderAccent: 'border-gold/40',
    goldBorderStrong: 'border-gold/70',
    goldHoverBorderStrong: 'hover:border-gold/70',
    goldBg10: 'bg-gold/10',
    goldBg20: 'border-gold/20',
    goldTextMuted: 'text-gold/60',
    sectionLabel: 'text-lapis',
    sectionBorder: 'border-lapis/15',
    sectionAccent: 'border-lapis/15',
    loadingIcon: 'text-lapis',
    selectionBg: 'selection:bg-lapis',
    error: 'text-red-400',
    errorBg: 'bg-red-600/80',
    debug: 'bg-white/60 border-stone-200 text-stone-700',
    debugInput: 'bg-white/80 border-stone-300 text-stone-800 placeholder:text-stone-400',
    debugDivider: 'border-stone-300',
    kbd: 'bg-stone-200 text-stone-700 border-stone-300',
  },
};

// Convenience alias: many UI elements (control bar, dropdowns, badges) always use
// the dark-mode gold regardless of current theme.  Destructuring avoids verbose
// `THEME.dark.*` references throughout the JSX.
export const GOLD = THEME.dark;
