#!/usr/bin/env node
/**
 * Builds the PR body for a Manifest Auto-Reconcile PR, describing exactly what
 * the bot did THIS run — so a reviewer scanning the (auto-merged) bot PRs can
 * see at a glance what changed, instead of a generic template.
 *
 * Reads (all optional, degrades gracefully):
 *   env ADDED_IDS        csv of feature ids the deterministic reconcile added
 *   env TRIGGER_SUBJECT  the push/merge commit message that triggered the run
 *   env TRIGGER_SHA      that commit's sha
 *   drift-before.json    output of `--json` captured BEFORE reconcile (for the
 *                        list of existing features whose source changed)
 *   feature-manifest.json  the FINAL manifest (post-enrichment) for coverage
 *   git status           the working-tree changes the bot will commit
 *
 * Prints markdown to stdout. No external deps.
 */
import { readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const root = process.env.FEATURE_MANIFEST_ROOT || '.';
const addedIds = (process.env.ADDED_IDS || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);
const triggerSubject = (process.env.TRIGGER_SUBJECT || '').split('\n')[0].trim() || '(a push to main)';
const triggerSha = (process.env.TRIGGER_SHA || '').slice(0, 7);

const readJSON = (p, fallback) => {
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch {
    return fallback;
  }
};

const manifest = readJSON(`${root}/feature-manifest.json`, { features: [] });
const byId = Object.fromEntries((manifest.features || []).map((f) => [f.id, f]));
const drift = readJSON(`${root}/drift-before.json`, {});
// Existing features whose source changed (re-baselined), excluding brand-new ones.
const updated = (drift.updated || [])
  .map((u) => u.id)
  .filter((id) => !addedIds.includes(id));

let changedFiles = [];
try {
  changedFiles = execSync('git status --porcelain', {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  })
    .split('\n')
    .map((l) => l.slice(3).trim())
    .filter(Boolean)
    .sort();
} catch {
  /* not a git repo (e.g. under test) — leave empty */
}

const out = [];
out.push('## 🤖 Auto-reconcile summary');
out.push('');
out.push(`**Triggered by:** ${triggerSubject}${triggerSha ? ` (\`${triggerSha}\`)` : ''}`);
out.push('');
out.push('**What the bot did:**');

if (addedIds.length) {
  out.push(`- ➕ Added ${addedIds.length} new feature(s) to the inventory:`);
  for (const id of addedIds) {
    const f = byId[id] || {};
    const tests = [...((f.tests && f.tests.unit) || []), ...((f.tests && f.tests.e2e) || [])];
    if (f.coverage === 'behavioral' && tests.length) {
      out.push(
        `  - \`${id}\` — coverage **behavioral**: wrote & gauntlet-proved ${tests
          .map((t) => `\`${t}\``)
          .join(', ')}`,
      );
    } else {
      out.push(
        `  - \`${id}\` — coverage **${f.coverage || 'none'}** (no verified test written; honest default)`,
      );
    }
  }
}

if (updated.length) {
  const shown = updated.slice(0, 12);
  const extra = updated.length - shown.length;
  out.push(
    `- 🔄 Re-baselined coverage hashes for ${updated.length} existing feature(s) whose source changed: ${shown
      .map((id) => `\`${id}\``)
      .join(', ')}${extra > 0 ? ` and ${extra} more` : ''}`,
  );
}

if (!addedIds.length && !updated.length) {
  out.push('- Reconciled the manifest to match the code (see files below).');
}

if (changedFiles.includes('docs/APP-STATE.md')) {
  out.push('- 📄 Regenerated `docs/APP-STATE.md`');
}

out.push('');
out.push('**Files in this PR:**');
out.push(changedFiles.length ? changedFiles.map((f) => `\`${f}\``).join(', ') : '(none)');
out.push('');
out.push(
  '<sub>Auto-generated by the Manifest Auto-Reconcile bot from what it actually did this run. ' +
    'This PR only touches the manifest, hashes, generated doc, and tests, so it auto-merges. ' +
    'Playbook: `docs/ci/manifest-autofix-instructions.md`.</sub>',
);

process.stdout.write(out.join('\n') + '\n');
