/**
 * transliterate-poets.js
 *
 * Documents how supabase/migrations/20260324000000_backfill_poet_name_en.sql
 * was generated.
 *
 * Usage (from repo root):
 *   node scripts/transliterate-poets.js > /tmp/output.sql
 *
 * Requires:
 *   - .env loaded (VITE_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY)
 *   - Node 18+ (fetch built-in)
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

// ---------------------------------------------------------------------------
// Transliteration map (mirrors src/utils/transliterate.js)
// ---------------------------------------------------------------------------
const ARABIC_TRANSLIT_MAP = {
  'ا': 'a',  'أ': 'a',  'إ': 'i',  'آ': 'aa', 'ٱ': 'a',
  'ب': 'b',  'ت': 't',  'ث': 'th', 'ج': 'j',  'ح': 'h',
  'خ': 'kh', 'د': 'd',  'ذ': 'dh', 'ر': 'r',  'ز': 'z',
  'س': 's',  'ش': 'sh', 'ص': 's',  'ض': 'd',  'ط': 't',
  'ظ': 'z',  'ع': "'",  'غ': 'gh', 'ف': 'f',  'ق': 'q',
  'ك': 'k',  'ل': 'l',  'م': 'm',  'ن': 'n',  'ه': 'h',
  'و': 'w',  'ي': 'y',  'ى': 'a',  'ة': 'h',  'ء': "'",
  'ؤ': "'",  'ئ': "'",
  '\u064E': 'a',  // fatha
  '\u064F': 'u',  // damma
  '\u0650': 'i',  // kasra
  '\u0651': '',   // shadda (handled by doubling)
  '\u0652': '',   // sukun
  '\u064B': 'an', // tanween fatha
  '\u064C': 'un', // tanween damma
  '\u064D': 'in', // tanween kasra
  '\u0670': 'a',  // alef superscript
  '،': ',', '؛': ';', '؟': '?', '»': '"', '«': '"',
  '\u200C': '', '\u200D': '', '\u200F': '', '\u200E': '',
};

function transliterate(text) {
  if (!text) return '';
  let result = '';
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    // Handle shadda: double the previous consonant
    if (ch === '\u0651') {
      const lastChar = result[result.length - 1];
      if (lastChar && lastChar !== ' ') result += lastChar;
      continue;
    }
    if (ch in ARABIC_TRANSLIT_MAP) {
      result += ARABIC_TRANSLIT_MAP[ch];
    } else if (/[\s\n]/.test(ch)) {
      result += ch;
    } else if (/[a-zA-Z0-9.,!?;:'"()\-\u2013\u2014\u2026]/.test(ch)) {
      result += ch; // pass through Latin chars
    }
    // Skip unrecognized Arabic diacritics/formatting chars
  }
  return result;
}

function titleCase(str) {
  return str
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, c => c.toUpperCase());
}

/**
 * Convert Arabic name to English transliteration with title casing.
 * Strips leading definite article to produce cleaner names.
 * e.g. "المتنبي" → "Al-Mutanabbi" style (basic: "Almtnby" with title-case)
 */
function toNameEn(arabicName) {
  const raw = transliterate(arabicName);
  return titleCase(raw);
}

// ---------------------------------------------------------------------------
// Main: fetch from Supabase and generate SQL
// ---------------------------------------------------------------------------
async function main() {
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceKey) {
    console.error('Missing VITE_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in environment.');
    process.exit(1);
  }

  const url = `${supabaseUrl}/rest/v1/poets?name_en=is.null&select=id,name&order=id&limit=2000`;
  const resp = await fetch(url, {
    headers: {
      apikey: serviceKey,
      Authorization: `Bearer ${serviceKey}`,
      Range: '0-1999',
    },
  });

  if (!resp.ok) {
    console.error(`Supabase fetch failed: ${resp.status} ${resp.statusText}`);
    process.exit(1);
  }

  const poets = await resp.json();
  console.error(`Fetched ${poets.length} poets missing name_en`);

  // Build SQL
  const ids = poets.map(p => p.id).join(', ');
  const cases = poets
    .map(p => {
      const nameEn = toNameEn(p.name).replace(/'/g, "''"); // escape SQL single-quotes
      return `  WHEN ${p.id} THEN '${nameEn}'`;
    })
    .join('\n');

  const sql = `-- Backfill English transliterations for poets missing name_en
-- Generated by scripts/transliterate-poets.js on ${new Date().toISOString().slice(0, 10)}
-- Source: transliterate() from src/utils/transliterate.js + title-case
-- Total: ${poets.length} poets

UPDATE public.poets
SET name_en = CASE id
${cases}
END
WHERE id IN (${ids})
  AND name_en IS NULL;
`;

  process.stdout.write(sql);
}

main();
