-- Backfill English transliterations for poets missing name_en
-- Generated by scripts/transliterate-poets.js on 2026-03-24
-- Algorithm: character-level Arabic→Latin map from src/utils/transliterate.js + title-case
-- Total: 938 poets updated

UPDATE public.poets
SET name_en = CASE id
  WHEN 3 THEN 'Abn Rshyq Alqyrwany'
  WHEN 4 THEN 'Abn ''Bd Rbh Alandlsy'
  WHEN 5 THEN 'Abw Al''Bas Almrsy'
  WHEN 6 THEN 'Abw Ashaq Alsaby'
  WHEN 7 THEN 'Mjhwl'
  WHEN 8 THEN 'Abn S''Yd Almghrby'
  WHEN 10 THEN 'Alshaf''Y'
  WHEN 11 THEN 'Abn Mqbl'
  WHEN 12 THEN 'Abw J''Fr Bn S''Yd Alandlsy'
  WHEN 13 THEN 'Styrh Al''Sybyh'
  WHEN 14 THEN 'Alwtar'
  WHEN 15 THEN 'Alhmany Alkwfy'
  WHEN 16 THEN 'Asma''Yl Sbry'
  WHEN 17 THEN '''Amr Bn Malk Alfzary'
  WHEN 18 THEN 'Abn Sarh ( Sarh ) Alshntryny'
  WHEN 19 THEN 'Thabt Qtnh'
  WHEN 20 THEN 'Sha''R Alhmra'''
  WHEN 21 THEN 'Y''Qwb Bn ''Ly Al Abrahym'
  WHEN 22 THEN 'Ma'' Al''Ynyn'
  WHEN 23 THEN 'Abn Alzqaq Alblnsy'
  WHEN 24 THEN 'Abn Alhaj Alnmyry'
  WHEN 25 THEN 'Amyh Aldany ( Alhkm Bn Aby Alslt )'
  WHEN 26 THEN 'Abrahym Najy'
  WHEN 27 THEN 'Nzhwn Bnt Alqla''Y Alghrnatyh'
  WHEN 28 THEN 'Alhkm Bn Aby Alslt'
  WHEN 29 THEN 'Hafz Abrahym'
  WHEN 30 THEN 'Sbt Abn Alt''Awydhy'
  WHEN 32 THEN 'Ahmd Tqy Aldyn'
  WHEN 33 THEN 'Abn Rshyq Alqyrwany Alazdy'
  WHEN 34 THEN 'Qys Bn Almlwh (Mjnwn Lyla)'
  WHEN 35 THEN '''Bd Alqadr Aljzayry'
  WHEN 36 THEN 'Abw Alqasm Alshaby'
  WHEN 37 THEN 'Abn Bajh Alandlsy'
  WHEN 39 THEN 'Abw Hyan Alnhwy Alandlsy'
  WHEN 40 THEN 'Abn Shrf Alqyrwany'
  WHEN 41 THEN 'Abrahym Twqan'
  WHEN 42 THEN 'Mnswr Bn Asma''Yl Alfqyh'
  WHEN 44 THEN '''Bd Allh Blfqyh'
  WHEN 45 THEN 'Abw Alfdl Bn Alahnf'
  WHEN 46 THEN '''Bd Alrhmn Aldakhl'
  WHEN 47 THEN 'Hazm Alqrtajny'
  WHEN 48 THEN 'Rwbh Bn ''Mrw Alth''Lby'
  WHEN 49 THEN 'Abn Mymwn Alqrtby'
  WHEN 50 THEN 'Ahmd Mtr'
  WHEN 51 THEN 'Mhmd Alasmr'
  WHEN 52 THEN 'Abn Allbanh Aldany'
  WHEN 53 THEN 'Adwnys'
  WHEN 54 THEN 'Alhsyn Bn ''Qyl'
  WHEN 55 THEN '''Ly Aljarm'
  WHEN 56 THEN 'Abw Alhsn Alnwry'
  WHEN 57 THEN 'Am Khald Alnmyryh'
  WHEN 58 THEN 'Alfrwkhy Abw Nsr Alawany'
  WHEN 59 THEN 'Nftwyh (Abw ''Bd Allh Alwasty Alazdy)'
  WHEN 60 THEN 'Ahmd Alsafy Alnjfy'
  WHEN 61 THEN 'Wsf Almtr Walshab'
  WHEN 62 THEN '''Mr Abn Aby Rby''H'
  WHEN 63 THEN '''Ly Mhmwd Th'
  WHEN 64 THEN '''Bd Al''Zyz Almqalh'
  WHEN 65 THEN '''Bd Aljbar Bn Hmdys'
  WHEN 66 THEN 'Abw Alhsn ''La Alwahdy'
  WHEN 67 THEN 'Jwrj Jrys Frh'
  WHEN 68 THEN '''Bd Alslam Al''Jyly'
  WHEN 69 THEN 'Khald Zryq'
  WHEN 70 THEN 'M''Yn Bsysw'
  WHEN 71 THEN 'Ahmd Mhrm'
  WHEN 72 THEN 'Qys Lbna'
  WHEN 73 THEN 'Abn ''Tyh Alandlsy'
  WHEN 74 THEN 'Halh Adrys'
  WHEN 76 THEN 'Yhya Alhmady'
  WHEN 77 THEN '''Bdallh Albrdwny'
  WHEN 79 THEN 'Ala''Ma Alttyly'
  WHEN 80 THEN 'Am Hkym Bnt Qarz'
  WHEN 81 THEN 'Zhyr Shykh Trab'
  WHEN 82 THEN 'Mthna Abrahym Dham'
  WHEN 83 THEN '''Mrw Bn Shas Alasdy'
  WHEN 84 THEN '''Bd Alhmyd Alsnwsy'
  WHEN 85 THEN 'S''Yd ''Ql'
  WHEN 87 THEN 'Tmym Albrghwthy'
  WHEN 88 THEN 'Alamam ''Ly Bn Aby Talb'
  WHEN 89 THEN 'Rab''H Al''Dwyh'
  WHEN 90 THEN 'Abw Alfdl Bn Al''Myd'
  WHEN 91 THEN 'Qys Bn Almlwh (Mjnwn Lyla )'
  WHEN 92 THEN 'Abn Alsyql Aljzry'
  WHEN 93 THEN '''Byd Allh Bn ''Bdallh Bn Tahr'
  WHEN 94 THEN 'Mhmd Alfayz Alqyrwany'
  WHEN 95 THEN 'Wly Aldyn Ykn'
  WHEN 96 THEN 'Abw Bkr Alkhaldy ( Alkhaldyan )'
  WHEN 97 THEN 'Abw Bkr Alsnwbry'
  WHEN 98 THEN 'Als''Lwky'
  WHEN 99 THEN 'Abw Alhda Alsyady'
  WHEN 100 THEN 'Alakhytl Alahwazy'
  WHEN 101 THEN 'Abw Nsr Alqshyry'
  WHEN 102 THEN 'Slym ''Nhwry'
  WHEN 103 THEN 'Sydy Mhmd Bn Alshykh Sydya'
  WHEN 104 THEN 'Abn Hdydh Allkhmy Alqyrwany'
  WHEN 105 THEN 'Najyh Bn Mhmd Alkatb'
  WHEN 106 THEN 'Abn Nma Alhly'
  WHEN 107 THEN 'Jmyl Bn M''Mr'
  WHEN 108 THEN 'J''Fr Alhly'
  WHEN 109 THEN 'Mstfa Alghlayyny'
  WHEN 110 THEN 'Abw S''Yd Alhjry'
  WHEN 111 THEN 'Twbh Bn Alhmyr Alkhfajy'
  WHEN 112 THEN '''Byd Allh Bn Ms''Wd Alhdhly'
  WHEN 113 THEN 'Ryth Bnt Al''Bas Alslmy'
  WHEN 114 THEN 'Abw ''Bd Allh Albghwy'
  WHEN 115 THEN 'Abn Bajh'
  WHEN 116 THEN 'Amyn Nasr Aldyn'
  WHEN 117 THEN '''Mr Alyafy'
  WHEN 118 THEN 'Abn Sarh Alandlsy'
  WHEN 119 THEN 'Abw Mnswr Alth''Alby'
  WHEN 120 THEN 'Abrahym Bn Syar Alnzam'
  WHEN 121 THEN 'Sdyd Aldwlh Abn Alanbary'
  WHEN 122 THEN 'Abn Wky'' Altnysy'
  WHEN 123 THEN 'Ghyda'' Alaywby'
  WHEN 124 THEN 'Ashj'' Alslmy'
  WHEN 125 THEN 'Abw Alhsn Althamy'
  WHEN 126 THEN '''Dy Bn Rby''H Almhlhl ( Alzyr )'
  WHEN 127 THEN 'Kazm Alkhdry'
  WHEN 128 THEN 'Ryth Bnt ''Asyh'
  WHEN 129 THEN '''Mad Aldyn Alasfhany'
  WHEN 130 THEN 'Abn Al''Sal'
  WHEN 131 THEN 'Abw Alfdl Alwlyd'
  WHEN 132 THEN 'Rshyd Aywb'
  WHEN 133 THEN '''Z Aldyn Abn M''Ql Almhlby'
  WHEN 134 THEN 'Abn Syd Alnas'
  WHEN 135 THEN '''Bd Alsadh Altfyly'
  WHEN 136 THEN 'Abw Alrby'' Slyman Almwhdy'
  WHEN 137 THEN 'Slyma Bnt Almhlhl'
  WHEN 138 THEN 'Ghazy Alqsyby'
  WHEN 139 THEN 'Abn Zylaq'
  WHEN 140 THEN 'Abn M''Swm Alhsny Alhsyny'
  WHEN 141 THEN 'Abw ''Ly Alkhwary Albyhqy'
  WHEN 142 THEN 'Ashaq Almwsly'
  WHEN 144 THEN 'Am Sry'' Alkndyh'
  WHEN 145 THEN 'Mhmd Bn Whyb Alhmyry'
  WHEN 146 THEN 'Alakhtl Alsghyr Bsharh Alkhwry'
  WHEN 147 THEN 'Tahr Zmkhshry'
  WHEN 148 THEN 'Abw ''Ly Almntqy'
  WHEN 149 THEN '''Dnan Alsaygh'
  WHEN 150 THEN 'Alhraq'
  WHEN 151 THEN 'Alkmyt Bn Zyd Alasdy'
  WHEN 152 THEN 'Yasr Mhmwd Alaqr'''
  WHEN 153 THEN 'Zky ''Ly Mhyl'
  WHEN 154 THEN 'Jwrj Jrdaq'
  WHEN 155 THEN 'Abw Kbyr Alhdhly'
  WHEN 156 THEN 'Abn Alzlazl'
  WHEN 157 THEN '''Marh Bn Salh ''Bd Almalk'
  WHEN 158 THEN 'Mjyr Aldyn Abn Tmym'
  WHEN 159 THEN 'Sh''Ra'' Mjhwlwn'
  WHEN 160 THEN 'Shhab Aldyn Abn Dmrdash'
  WHEN 161 THEN 'Syf Aldyn Almshd'
  WHEN 162 THEN 'Abw J''Fr Alb''Yrh'
  WHEN 163 THEN '''Atkh Alkhzrjy'
  WHEN 164 THEN 'Abn M''Swm Almdny'
  WHEN 165 THEN 'Ghazy Bn ''Aly'
  WHEN 167 THEN 'Hlymh Alhdryh'
  WHEN 168 THEN 'Qasm Hdad'
  WHEN 169 THEN 'Abn Zfr Alsqly'
  WHEN 170 THEN '''Rqlh Alklby'
  WHEN 171 THEN '''Ayshh Alba''Wnyh'
  WHEN 172 THEN 'Slyman Alswlh'
  WHEN 173 THEN '''Bd Alhkym Bn ''Amr Alhjry'
  WHEN 174 THEN 'Mhmd Ahmd Almjaly'
  WHEN 175 THEN 'Ryad Mnswr'
  WHEN 176 THEN '''Ayshh Bnt Ahmd Alqrtbyh'
  WHEN 177 THEN 'Sfwan Bn Adrys Altjyby'
  WHEN 178 THEN 'Hydr Bn Slyman Alhly'
  WHEN 179 THEN '''Bd Alqadr Bdran'
  WHEN 180 THEN '''Byd Allh Bn Alhr Alj''Fy'
  WHEN 181 THEN 'Mhmwd Almshhdany'
  WHEN 182 THEN 'Mrsy Shakr Tntawy'
  WHEN 183 THEN 'Mhdy Albghdady'
  WHEN 184 THEN 'Mhdy Hjy'
  WHEN 185 THEN 'Abrahym Alyazjy'
  WHEN 186 THEN 'Qryf Alklby'
  WHEN 187 THEN 'Abn Lwlw'
  WHEN 188 THEN '''Ly Shwqy'
  WHEN 189 THEN 'Abrahym Altbatbayy'
  WHEN 190 THEN '''Mad Aldyn Alasbhany'
  WHEN 191 THEN 'Abn Aby ''Thman Alqrtby'
  WHEN 192 THEN 'Abn Qrnas'
  WHEN 193 THEN '''Bd Alrhmn Alshyly'
  WHEN 194 THEN 'Ans Alhjar'
  WHEN 195 THEN 'Abw Alkhtab ''Mr Bn Mhmd Almryy'
  WHEN 196 THEN 'Hnd Jaryh Alshatby'
  WHEN 197 THEN 'Zyad Alnhmy'
  WHEN 198 THEN 'Abn ''Bdwn'
  WHEN 199 THEN '''Bdalmhsn Bn Mrzwq Alqthamy'
  WHEN 200 THEN 'Alwzyr Abw Hfs Bn Brd Alasghr'
  WHEN 201 THEN 'Alsha''R Altwnsy'
  WHEN 202 THEN 'Almfty ''Bd Alltyf Fth Allh'
  WHEN 203 THEN '''Ayshh Altymwryh'
  WHEN 204 THEN 'Abw Mhmd ''Bd Allh Al''Sal'
  WHEN 205 THEN '''La'' Aldyn Alwda''Y'
  WHEN 206 THEN 'Ahmd Bn Talwt Alblnsy Alshbrby'
  WHEN 207 THEN 'Abn ''Mran Alkfyf'
  WHEN 208 THEN 'Alaqlyshy'
  WHEN 209 THEN 'Mty'' Bn Ayas'
  WHEN 210 THEN '''Bd Allh Alkhfajy'
  WHEN 211 THEN '''Aly Almalky'
  WHEN 212 THEN '''Bdh Fayz Alzbydy'
  WHEN 213 THEN 'Abn Alhaj Alblfyqy'
  WHEN 214 THEN 'Swyd Bn Shbyb'
  WHEN 215 THEN 'Almdayh Alnbwyh'
  WHEN 216 THEN 'Mykhayyl Khyr Allh Wyrdy'
  WHEN 217 THEN 'Abn Shykhan Alsalmy'
  WHEN 218 THEN 'Ywsf Althalth'
  WHEN 219 THEN 'D. ''Mrw Frj Ltyf'
  WHEN 220 THEN 'Albdy'' Aldmshqy'
  WHEN 221 THEN 'Alaswd Bn Y''Fr Alnhshly'
  WHEN 222 THEN 'Abn Alkhlwf'
  WHEN 223 THEN 'Abw Al''Rb Alsqly'
  WHEN 224 THEN 'Ywsf Althalth - Mlk Ghrnath'
  WHEN 225 THEN 'Hna'' Mhmd'
  WHEN 226 THEN 'Fwad Alkhtyb'
  WHEN 227 THEN 'Alnsyby Alqwsy'
  WHEN 228 THEN 'Alshryf Alghrnaty'
  WHEN 229 THEN 'Mhmd Alsaq'
  WHEN 230 THEN 'Abwalthna'' Shhab Aldyn Mhmwd Alalwsy'
  WHEN 231 THEN 'Mhmd Khdyr'
  WHEN 232 THEN 'Alhsyn Bn ''Ly Bn Ahmd'
  WHEN 233 THEN 'Mhyy Aldyn Bn ''Bd Alzahr'
  WHEN 234 THEN 'Abn Alabar Alqda''Y Albnlsy'
  WHEN 235 THEN 'Shl Alghrnaty'
  WHEN 236 THEN 'Mwfq Aldyn Bn Aby Alhdyd'
  WHEN 237 THEN 'Mhmd ''Thman Jlal'
  WHEN 238 THEN 'Mhmd Alkhlkhaly'
  WHEN 239 THEN 'Ahmd Alkashf'
  WHEN 240 THEN 'Am Qys Aldbyh'
  WHEN 241 THEN 'Aslam ''Kryh'
  WHEN 242 THEN '''Bas ''Ly Al''Skr'
  WHEN 243 THEN 'Hydr Alhly'
  WHEN 244 THEN 'Abn Fdal Alhlwany'
  WHEN 245 THEN 'J''Fr Alhly Alnjfy'
  WHEN 246 THEN 'Abw Mslm Albhlany'
  WHEN 247 THEN 'Abn Htyml'
  WHEN 248 THEN 'Abw ''Bd Allh Alhlwany'
  WHEN 249 THEN 'Mhsn Abw Alhb'
  WHEN 250 THEN 'Mzyd Alhly'
  WHEN 251 THEN 'Aml Dnql'
  WHEN 252 THEN 'Hamd Abw Alghyt'
  WHEN 253 THEN 'Ahmd Fars Alshdyaq'
  WHEN 254 THEN 'Bha'' Aldyn Alsyady'
  WHEN 255 THEN 'Salh Th ( Zmyan Ghdyr )'
  WHEN 256 THEN 'Dhw Alwzartyn Abw Bkr Bn ''Mar'
  WHEN 257 THEN 'Hnzlh'
  WHEN 258 THEN 'Abn Jbyr'
  WHEN 259 THEN 'Nsr Allh Alhayry'
  WHEN 260 THEN 'Mwsa Altalqany'
  WHEN 261 THEN 'Hsyn Al''Rwy'
  WHEN 262 THEN '''Sam Aldyn Al''Mry'
  WHEN 263 THEN 'Abw Dwad Alayady'
  WHEN 264 THEN 'Abn Jzy Alklby'
  WHEN 265 THEN 'Myqat Alrajhy'
  WHEN 266 THEN 'Flwra Qazan'
  WHEN 267 THEN 'Almwyd Fy Aldyn'
  WHEN 268 THEN '''Bd Al''Zyz Alfshtaly'
  WHEN 269 THEN 'Adyb Ashaq'
  WHEN 270 THEN 'Abn Alabar Alashbyly'
  WHEN 271 THEN '''Yynh Bn ''Bd Alrhmn Abw Almnhal'
  WHEN 272 THEN 'Mhmd Bn Ahmd Bn Rshyd Mwla Almhdy'
  WHEN 273 THEN 'Zyd Bn ''Mrw Bn Nfyl'
  WHEN 274 THEN '''Ly Afndy Aldrwysh'
  WHEN 275 THEN 'Abn Hdhyl'
  WHEN 276 THEN 'Almnazy'
  WHEN 277 THEN 'Amyh Bn ''Bd Al''Zyz Aldany'
  WHEN 278 THEN 'Slyman Bn Whb'
  WHEN 279 THEN 'Almtran Jrmanws'
  WHEN 280 THEN 'Abw Alfth Bn Jna'
  WHEN 281 THEN 'Mhy Aldyn Bn ''Rby'
  WHEN 282 THEN 'Mhdy Altalqany'
  WHEN 283 THEN 'Abn S''D Alkhyr Alblnsy'
  WHEN 284 THEN '''Mr Alraf''Y'
  WHEN 285 THEN 'Hsan Ahmd Qmhyh'
  WHEN 286 THEN 'S''Dyh Mfrh'
  WHEN 287 THEN 'Mhmd Al''Yd Al Khlyfh'
  WHEN 288 THEN 'Abn Sahb Alslah ( Abn Almnasf )'
  WHEN 289 THEN 'Frwh Bn Nwfl Alashj''Y'
  WHEN 290 THEN 'Alhsn Bn Bshr Bn Alamdy'
  WHEN 291 THEN '''Bdalrhym Bdr'
  WHEN 292 THEN '''Bdallh Jdy'
  WHEN 293 THEN 'Rym Slyman Alkhsh'
  WHEN 294 THEN '''La'' Khlf'
  WHEN 295 THEN 'Mwsa Shrarh'
  WHEN 296 THEN 'Alakhyf Bn Mlyk'
  WHEN 297 THEN 'Zahm Mhmwd Khwrshyd'
  WHEN 298 THEN 'Mhyy Aldyn Abn Alshhrzwry'
  WHEN 299 THEN 'Abrahym Bn Hlal Bn Zhrwn'
  WHEN 300 THEN 'Dhbyh Bnt Byshh Alfhmyh'
  WHEN 301 THEN 'Alqasm Sdr Alafadl'
  WHEN 302 THEN 'Ahmd Bn ''Ly Alkhtyb'
  WHEN 303 THEN 'Rmdan ''Bd Alhmyd Zydan'
  WHEN 304 THEN 'Hbysh Bn ''Bd Allh Alhmdany'
  WHEN 305 THEN 'Mhmd S''D ''Ysws'
  WHEN 306 THEN 'Ahmd Alsabwny'
  WHEN 307 THEN 'Mhmd Bn ''Ly Bn Aby Mrwan'
  WHEN 308 THEN '''Bad Bn Shdad Alyrbw''Y'
  WHEN 309 THEN '''Dy Bn Hatm Altayy'
  WHEN 310 THEN 'Mhmd Bn Mslmh Alashbyly'
  WHEN 311 THEN 'Abn Alskwn Alkatb Alhly'
  WHEN 312 THEN 'Abw Alhsn Abn Alnrsy'
  WHEN 313 THEN '''Bd Al''Zyz Aljasr'
  WHEN 314 THEN '''Mr Hza'''
  WHEN 315 THEN '''Bd Almhymn Alhdrmy'
  WHEN 316 THEN 'Abn Alfdl Albghdadhy'
  WHEN 318 THEN 'Alfrwsyh'
  WHEN 319 THEN 'Zfr Bn Alharth Alklaby'
  WHEN 321 THEN 'Thabt Bn Snan Alsaby'
  WHEN 322 THEN 'Mhmd Tahr Aljblawy'
  WHEN 323 THEN 'Nahdh Alhlby'
  WHEN 324 THEN 'Ayman Almhmdawy'
  WHEN 325 THEN '''Bd Al''Zyz Bn Zrarh Alklaby'
  WHEN 326 THEN '''Bd Allh Bn ''Ly Alkhlyly'
  WHEN 327 THEN 'Ma Qyl Fy Alnaqh Walqwafl'
  WHEN 328 THEN 'Jasm Alshyh'
  WHEN 329 THEN '''Ly Bn Mhmd Althamy'
  WHEN 330 THEN 'Mhmwd Qhtan'
  WHEN 331 THEN 'Ysra Hza'''
  WHEN 332 THEN 'Mhsn Alamyn'
  WHEN 333 THEN 'Mhmd Hsyn Al Yasyn'
  WHEN 334 THEN 'Mhmd S''Yd Mhmd Al''Tyq'
  WHEN 335 THEN 'Abw ''Bdh Alwzyr'
  WHEN 336 THEN '''Mrh Bnt Rwahh Alansaryh'
  WHEN 337 THEN 'Hna Bk Alas''D Bn Aby S''B'
  WHEN 338 THEN 'Lbyd Bn Rby''H Al''Amry'
  WHEN 339 THEN 'Zyn Al''Abdyn Aldbyby'
  WHEN 340 THEN 'Mhmd Almqrn'
  WHEN 341 THEN 'Ahlam Bnawy'
  WHEN 342 THEN 'Alhbsy'
  WHEN 343 THEN 'Arwa Bnt Alharth'
  WHEN 344 THEN 'Yasr Alatrsh'
  WHEN 345 THEN 'Mhnd Hlymh'
  WHEN 346 THEN 'Yhya Qsady'
  WHEN 347 THEN 'Alhsn Bn ''Mrw Alabady'
  WHEN 348 THEN 'Mhmd Alhmshry'
  WHEN 349 THEN 'Mhmd Kmal'
  WHEN 350 THEN 'Alhdad Alqysy'
  WHEN 351 THEN '''Amr Bn Alzrb Al''Dwany'
  WHEN 352 THEN 'Bsharh Alkhwry'
  WHEN 353 THEN 'Mhmd Hmdy Ghanm'
  WHEN 354 THEN 'Zky Alsbyhawy'
  WHEN 355 THEN 'Salh Th'
  WHEN 356 THEN 'Al''Yzar Bn Alakhns Altayy'
  WHEN 357 THEN 'Abn Aby Alasb'''
  WHEN 358 THEN 'Khtam Hmwdh'
  WHEN 359 THEN 'Abnh Hdhaq Alhnfy'
  WHEN 360 THEN 'Abn Alnbyh'
  WHEN 362 THEN '''Bd Almjyd Qasm Altrshany'
  WHEN 363 THEN 'Rayth Bnt Shyzm Alnmyryh'
  WHEN 364 THEN 'Tqa Almrsy'
  WHEN 365 THEN 'Mrh Bn Mhkan Als''Dy'
  WHEN 366 THEN 'Khshan Khshan'
  WHEN 367 THEN 'Khald Mjml'
  WHEN 368 THEN 'Lsan Aldyn Alkhtyb'
  WHEN 369 THEN 'Mhmwd Sbty'
  WHEN 370 THEN 'Salh Alshrnwby'
  WHEN 371 THEN 'Thwrat Altghyyr Al''Rbyh'
  WHEN 372 THEN '''Bd Alnasr ''Lywy Al''Bydy'
  WHEN 373 THEN 'S''Yd Bn Mslm Al''Many'
  WHEN 374 THEN '''Bd Alrhym Ahmd Alsghyr(Almaskh)'
  WHEN 375 THEN 'Mhmd Bn Babkr Alfadly'
  WHEN 376 THEN '''Bdallh Alndym'
  WHEN 377 THEN 'Syf Alrhby'
  WHEN 378 THEN 'Bhyjh Msry Adlby'
  WHEN 379 THEN 'Rashd Hsyn'
  WHEN 380 THEN 'Dmd Kazm Alwsmy'
  WHEN 381 THEN 'Myr ''Ly Abw Tbykh'
  WHEN 382 THEN 'Abw Alyqzan Albhlany'
  WHEN 383 THEN '''Bd Albaqy Al''Mry Alfarwqy'
  WHEN 384 THEN 'Shrf Aldyn Albwsyry'
  WHEN 385 THEN 'Mhmd Mstfa Ma'' Al''Ynyn'
  WHEN 386 THEN 'Abw Ashaq Aljrjany'
  WHEN 387 THEN 'Alwzyr Almghrby'
  WHEN 388 THEN 'Khlyl Mrdm Bk'
  WHEN 389 THEN 'Abrahym Bn Al''Bas Alswly'
  WHEN 390 THEN 'Almnftl'
  WHEN 391 THEN '''Rwh Bn Adyh'
  WHEN 392 THEN 'Abn Makwla'
  WHEN 393 THEN 'Alqady ''Bd Alwhab Almalky'
  WHEN 394 THEN 'Abw Mnswr Abn Mhdy Alkhwafy'
  WHEN 395 THEN 'Dhw Allsanyn Alntnzy'
  WHEN 396 THEN 'Qys Bn ''Asm Almnqry'
  WHEN 397 THEN 'Tahr Ywns Hsyn'
  WHEN 398 THEN 'Jabr Alkazmy'
  WHEN 399 THEN '''Bd Alhlym Abrahym ''Bd Alhlym'
  WHEN 400 THEN '''Bdalhsyn Alazry'
  WHEN 401 THEN 'Abn Alzhyr Alarbly'
  WHEN 402 THEN 'Abw Alhythm Alm''Ry Akhw Aby Al''La'''
  WHEN 403 THEN 'Mrsy Shakr Altntawy'
  WHEN 404 THEN 'Lyla Alakhylyh'
  WHEN 405 THEN 'Mhmd ''Ly Zyn Aldyn'
  WHEN 406 THEN 'Alamam Alshwkany'
  WHEN 407 THEN 'Abn Jzy Alklby Mhrr Rhlh Abn Btwth'
  WHEN 408 THEN 'Alkhybry Alkharjy'
  WHEN 409 THEN 'Almlk Alm''Z Mhyy Aldyn Alaywby'
  WHEN 410 THEN 'Alshykh Alryys Abw Nsr Alqayny'
  WHEN 411 THEN 'Qstaky Alhmsy'
  WHEN 412 THEN 'Abn Rshyd Albghdady'
  WHEN 413 THEN '''Mr Alansy'
  WHEN 414 THEN 'Tanyws ''Bdh'
  WHEN 415 THEN 'Abn Asd Alfarqy'
  WHEN 416 THEN 'Alkmyt Bn M''Rwf Alasdy'
  WHEN 417 THEN 'Abn Alafrnjyh'
  WHEN 418 THEN 'Almfty Fth Allh'
  WHEN 419 THEN 'Abw Alqasm Alzahy'
  WHEN 420 THEN '''Bd Alltyf Alsyrfa'
  WHEN 421 THEN 'Abn Fayd Albhrany'
  WHEN 422 THEN 'As''D Trad'
  WHEN 423 THEN 'Mhmd Twfyq ''Ly'
  WHEN 424 THEN 'Alslamy'
  WHEN 425 THEN 'Lqyt Bn Zrarh Aldarmy'
  WHEN 426 THEN 'Abw ''Amr Aljrjany'
  WHEN 427 THEN '''Ly Aljshy'
  WHEN 428 THEN 'Zhyr Aldyn Alrwdhrawry'
  WHEN 429 THEN 'Abw ''Thman Alkhaldy ( Alkhaldyan )'
  WHEN 430 THEN 'Abn Harwn Alasbhy'
  WHEN 431 THEN 'Abw Mshr'
  WHEN 432 THEN '''Bdalslam Alshty'
  WHEN 433 THEN 'Ltf Allh Bn Alm''Afy'
  WHEN 434 THEN 'Abrahym Alahdb'
  WHEN 435 THEN 'Abw Alshys Mhmd'
  WHEN 436 THEN 'Mhmd Bn Aby Amyh'
  WHEN 437 THEN 'Alwzyr Fkhr Aldyn Abn Mkans Alqbty'
  WHEN 438 THEN 'Ahmd Nsym'
  WHEN 439 THEN '''Qyl Bn ''Lfh'
  WHEN 440 THEN 'Salm Altryhy'
  WHEN 441 THEN 'Ahmd Zky Abw Shady'
  WHEN 442 THEN '''Bdalhsyn Aljwahry'
  WHEN 443 THEN 'Almrymy'
  WHEN 444 THEN 'Amyn Aljndy Alhmsy'
  WHEN 445 THEN 'Khlyl Nasyf Alyazjy'
  WHEN 446 THEN 'Abw ''Ly Abn Fwrjh'
  WHEN 447 THEN 'Abw Aljwayz Alwasty'
  WHEN 448 THEN 'Ahmd Sfwt Aldyb'
  WHEN 449 THEN 'Asma''Yl Sry Aldhshan'
  WHEN 450 THEN 'Hsyn Mqdady'
  WHEN 451 THEN '''Bas Almla ''Ly Alnjfy'
  WHEN 452 THEN 'Nasyf Alyazjy'
  WHEN 453 THEN 'Abn Mknsh Alaskndrany'
  WHEN 454 THEN 'Abn Malk'
  WHEN 455 THEN 'Yhya Abn Albhtry'
  WHEN 456 THEN 'Mhnd Msh''L ''Bd Al''Zyz'
  WHEN 457 THEN 'Jlylh Bnt Mrh Alshybanyh'
  WHEN 458 THEN 'Zky Mbark'
  WHEN 459 THEN 'Asma'' Bnt Aby Bkr'
  WHEN 460 THEN 'Zynb Fwaz'
  WHEN 461 THEN '''Bd Almhsn Alswry Bn Ghlbwn'
  WHEN 462 THEN 'Abw Alysr Alm''Ry'
  WHEN 463 THEN 'Alhsyn Bn Ahmd Alsnjary'
  WHEN 464 THEN 'Jhad Al''Bady'
  WHEN 465 THEN 'Abrahym Alhsry'
  WHEN 466 THEN 'Abw Alshghb Al''Bsy'
  WHEN 467 THEN 'Abn Hdydh'
  WHEN 468 THEN 'Abw Alhsn Alsnjany'
  WHEN 469 THEN 'Abnh ''Qyl Bn Aby Talb'
  WHEN 470 THEN '''Bdalkrym Almmtn'
  WHEN 471 THEN 'Am Aby Alhsn Alslamy'
  WHEN 472 THEN 'Y''Qwb Alhaj J''Fr Altbryzy'
  WHEN 473 THEN 'Mhyy Aldyn Alshhrzwry'
  WHEN 474 THEN 'Abw Al''Bas Ala''Ma Almlky'
  WHEN 475 THEN 'Alkhlyl Bn Ahmd Alfrahydy'
  WHEN 476 THEN 'Abw Alfdl Almykaly'
  WHEN 477 THEN 'Lyla Al''Fyfh'
  WHEN 478 THEN 'Abrahym Tlhh'
  WHEN 479 THEN 'Alhsyn Bn Asd Al''Amry'
  WHEN 480 THEN 'Shyryn Shyhh'
  WHEN 481 THEN 'Abw Alhsn Aljwhry'
  WHEN 482 THEN 'Mkhtar Bn Alhsyn Aljmhy Albyhqy'
  WHEN 483 THEN 'Mqys Bn Sbabh'
  WHEN 484 THEN 'Lyla Bnt Slma'
  WHEN 485 THEN 'Abw J''Fr Albny'
  WHEN 486 THEN 'Ans Abrahym Aldghym'
  WHEN 487 THEN 'Abw Alhsn Aln''Ymy'
  WHEN 488 THEN 'Almrtda Alshhrzwry'
  WHEN 489 THEN 'Altbyb Abn Alktany Almdhhjy'
  WHEN 490 THEN 'Fatmh Bnt Alahjm Alkhza''Yh'
  WHEN 491 THEN 'Mrym Ymq ( Zahyh Bnt Albhr )'
  WHEN 492 THEN 'Arwa Bnt ''Bd Almtlb'
  WHEN 493 THEN '''Mr Tqy Aldyn Alraf''Y'
  WHEN 494 THEN 'Rashd Bn Khmys Alhbsy'
  WHEN 495 THEN 'Bshyr Alsalh'
  WHEN 496 THEN 'Abn Shkhys'
  WHEN 497 THEN '''Ly Bn Fdal Almjash''Y'
  WHEN 498 THEN 'Abn Qdyb Alban Alhlby'
  WHEN 499 THEN 'Alhaj Ghlwj'
  WHEN 500 THEN 'Mhmd Alshadhly Khznh Dar'
  WHEN 501 THEN 'Abw ''Ly Alzrghyly Alzwzny'
  WHEN 502 THEN 'Ahmd Salm S''Yd Ba''Tb'
  WHEN 503 THEN 'Ahmd Alqwsy'
  WHEN 504 THEN '''Z Aldwlh Sdyd Almlk Abn Mnqdh'
  WHEN 505 THEN 'Abw Ghalb Alwasty'
  WHEN 506 THEN '''Bd Alhady Shlylh'
  WHEN 507 THEN 'Ahmd Khald Almshary'
  WHEN 508 THEN 'Alhsyn Bn ''Ly Bn Aby Talb'
  WHEN 509 THEN 'Qtylh Bnt Alndr'
  WHEN 510 THEN 'Nazk Almlaykh'
  WHEN 511 THEN 'Shhab Aldyn Alalwsy'
  WHEN 512 THEN 'Mhmwd Hsn Asma''Yl'
  WHEN 513 THEN '''Amryh Alkthyb'
  WHEN 514 THEN '''Ly Ahmd Qly'
  WHEN 515 THEN 'Baqr Al''Tar'
  WHEN 516 THEN 'Naf'' Mhmd Alnaf'''
  WHEN 517 THEN 'Albajy Alms''Wdy'
  WHEN 518 THEN 'Hydr Altmymy'
  WHEN 519 THEN 'Abtsam Albrghwthy'
  WHEN 520 THEN 'Ahsan Albny'
  WHEN 521 THEN 'Adrys Al''Mrawy'
  WHEN 522 THEN 'Alasbgh Alqrshy'
  WHEN 523 THEN '''Mrw Bn M''Dy Krb'
  WHEN 524 THEN 'Mhsn Aljwahry'
  WHEN 525 THEN '''Ly Qshaqsh'
  WHEN 526 THEN '''Mran Alm''Mry'
  WHEN 527 THEN 'Mhmd Alrwas'
  WHEN 528 THEN 'Wrdh Alyazjy'
  WHEN 529 THEN 'Alshmakh Bn Drar Aldhbyany'
  WHEN 530 THEN 'Th Hsyn'
  WHEN 531 THEN 'Alyas Abw Shbkh'
  WHEN 532 THEN '''Dnan Alghryfy'
  WHEN 533 THEN 'Fkhr Aldyn Abn Hbyrh'
  WHEN 534 THEN '''Ly Qwadry'
  WHEN 535 THEN 'Kn''An Almwswy'
  WHEN 536 THEN 'Malk Bn Nmt Alhmdany'
  WHEN 537 THEN 'Almfdy Zkrya'
  WHEN 538 THEN 'Hsn Qftan'
  WHEN 539 THEN 'Mky Bn Hbyrh'
  WHEN 540 THEN 'Ryth Bnt ''Asm Alhwaznyh'
  WHEN 541 THEN 'Trky Alm''Yny'
  WHEN 542 THEN 'Kfa Khdr'
  WHEN 543 THEN 'Skhr Bn ''Mrw Alslmy'
  WHEN 544 THEN 'Mhmwd Mflh'
  WHEN 545 THEN 'Fras Dyry'
  WHEN 546 THEN '''Mr Abw Ryshh'
  WHEN 547 THEN 'Alwjyh Alnhwy Aldryr Abn Aldhan'
  WHEN 548 THEN '''Bdallh Alkhdry'
  WHEN 549 THEN 'Slyman Bn Slyman Alnbhany'
  WHEN 550 THEN 'Dhw Almfakhr Alhmdhany Alnyrmany'
  WHEN 551 THEN '''Ly Alrmdan Alshhyd'
  WHEN 552 THEN 'Nwry Sraj Alwayly'
  WHEN 553 THEN 'Abn Hmam'
  WHEN 554 THEN 'Abn Altlmydh'
  WHEN 555 THEN 'Th Alrawy'
  WHEN 556 THEN '''Rqlh Alklby Aldmshqy'
  WHEN 557 THEN '''Bdh Bn Altbyb'
  WHEN 558 THEN 'Alrady Abn Alm''Tmd Bn ''Bad'
  WHEN 559 THEN '''La'' Salm'
  WHEN 560 THEN 'Abw ''Dy Alm''Ry'
  WHEN 561 THEN 'Hajb Alfyl'
  WHEN 562 THEN 'Nbwyh Mwsa'
  WHEN 563 THEN 'Ahmd Fthy'
  WHEN 564 THEN 'Mhmd Tymwr'
  WHEN 565 THEN 'Farwq Jwydh'
  WHEN 566 THEN '''Bdalhsyn Alhly'
  WHEN 567 THEN 'Wald Asamh Bn Mnqdh'
  WHEN 568 THEN 'Mhmd ''Bd Alhfyz Alqsab'
  WHEN 569 THEN '''Bdallh Bn Salh Al''Bdallh'
  WHEN 570 THEN 'Krym Aln''Man'
  WHEN 571 THEN 'Nsyb Alnkdy'
  WHEN 572 THEN 'Slyman Alhsn'
  WHEN 573 THEN 'Mfdy Zkrya'
  WHEN 574 THEN 'Alhsn Bn Whb'
  WHEN 575 THEN 'Am Qrfh'
  WHEN 576 THEN 'Alahwl Alhsny'
  WHEN 577 THEN 'Alakhtl Alsghyr'
  WHEN 578 THEN 'Kwkb Albdry'
  WHEN 2611 THEN 'Almrar Bn Mnqdh'
  WHEN 2621 THEN 'Al''Ywq Bnt Ms''Wd'
  WHEN 2631 THEN 'Alaqr'' Bn M''Adh'
  WHEN 2632 THEN 'Jbyha'' Alashj''Y'
  WHEN 2635 THEN 'Mrwan Bn Aby Hfsh'
  WHEN 2636 THEN '''Rwh Bn Hzam'
  WHEN 2637 THEN 'Khald Bn Alwlyd'
  WHEN 2638 THEN 'Fatmh Alzhra'''
  WHEN 2639 THEN '''Ly Bn Alhsyn'
  WHEN 2645 THEN '''Atkh Bnt Zyd'
  WHEN 2648 THEN 'Abn Zryq Albghdady'
  WHEN 2655 THEN '''Bd Allh Bn Almbark'
  WHEN 2656 THEN 'Abw ''Ly Albsyr'
  WHEN 2660 THEN 'Abn Tbatba Al''Lwy'
  WHEN 2664 THEN '''Bd Almlk Alharthy'
  WHEN 2665 THEN 'Ahmd Bn Tyfwr'
  WHEN 2666 THEN 'Abn Ymwt'
  WHEN 2673 THEN 'Y''Qwb Bn Alrby'''
  WHEN 2674 THEN 'Abn Alashd Albhdly'
  WHEN 2678 THEN 'Yzyd Almhlby'
  WHEN 2681 THEN 'Yhya Bn Zyad Alharthy'
  WHEN 2684 THEN 'Wjyh Aldwlh Alhmdany'
  WHEN 2689 THEN 'Dhw Alnwn Almsry'
  WHEN 2690 THEN 'Abn Mknsh'
  WHEN 2697 THEN 'Ahmd Bn Aby Fnn'
  WHEN 2698 THEN 'Abw Alhsyn Alnwry'
  WHEN 2699 THEN 'Abw Alhsn Aljrjany'
  WHEN 2703 THEN 'Bdy'' Alzman Alhmdhany'
  WHEN 2706 THEN 'Abzwn Al''Many'
  WHEN 2707 THEN 'Al''Bas Bn Alahnf'
  WHEN 2708 THEN 'Ibrahym Alswly'
  WHEN 2709 THEN 'Abn Alm''Tz'
  WHEN 2714 THEN 'D''Bl Alkhza''Y'
  WHEN 2716 THEN 'Abn Draj Alqstly'
  WHEN 2717 THEN 'Abw Al''Yna'''
  WHEN 2718 THEN 'Abn ''Bd Rbh'
  WHEN 2719 THEN 'Alahnf Al''Kbry'
  WHEN 2720 THEN 'Abw Alshmqmq'
  WHEN 2721 THEN 'Alrady Ballh'
  WHEN 2722 THEN 'Abw Bkr Alkhwarzmy'
  WHEN 2724 THEN 'Abw Alfth Albsty'
  WHEN 2725 THEN 'Alsry Alrfa'''
  WHEN 2726 THEN 'Alkhbz Arzy'
  WHEN 2727 THEN 'Althamy'
  WHEN 2728 THEN 'Abn Hjaj'
  WHEN 2729 THEN 'Alsahb Bn ''Bad'
  WHEN 2730 THEN 'Alwawa'' Aldmshqy'
  WHEN 2731 THEN 'Mhyar Aldylmy'
  WHEN 2732 THEN 'Ibrahym Bn Hrmh'
  WHEN 2733 THEN '''Bd Almhsn Alswry'
  WHEN 2734 THEN 'Srdr'
  WHEN 2735 THEN 'Dyk Aljn'
  WHEN 2736 THEN 'Abn Alhbaryh'
  WHEN 2741 THEN 'Mhmwd Alwraq'
  WHEN 2742 THEN 'Abw Dulamh'
  WHEN 2743 THEN 'Sry'' Alghwany'
  WHEN 2744 THEN 'Abn Dawd Alzahry'
  WHEN 2745 THEN 'Abn Dryd Alazdy'
  WHEN 2746 THEN 'Kshajm'
  WHEN 2748 THEN 'Alnash'' Alakbr'
  WHEN 2751 THEN 'Abw Hlal Al''Skry'
  WHEN 2752 THEN 'Alsnwbry'
  WHEN 2753 THEN 'Harwn Alrshyd'
  WHEN 2754 THEN 'Abn Myadh'
  WHEN 2755 THEN 'Salh Bn ''Bd Alqdws'
  WHEN 2756 THEN 'Abn Alzyat'
  WHEN 2758 THEN 'Alhsyn Bn Aldhak'
  WHEN 2759 THEN '''Ly Bn Aljhm'
  WHEN 2761 THEN 'Alkhlyl Alfrahydy'
  WHEN 2762 THEN 'Mhmd Bn Hazm Albahly'
  WHEN 2764 THEN 'Mstfa Albaby Alhlby'
  WHEN 2765 THEN 'Smnwn Almhb'
  WHEN 2766 THEN 'Jhzh Albrmky'
  WHEN 2767 THEN '''Lyh Bnt Almhdy'
  WHEN 2769 THEN 'Abw Bkr Alshbly'
  WHEN 2771 THEN 'Yhya Alghzal'
  WHEN 2772 THEN '''Rqlh Aldmshqy'
  WHEN 2773 THEN 'Abn Whyb Alhmyry'
  WHEN 2774 THEN 'Alkhrymy'
  WHEN 2775 THEN 'Abw Hfan Almhzmy'
  WHEN 2776 THEN 'Alwzyr Almhlby'
  WHEN 2778 THEN 'Abw Alhsn Alslamy'
  WHEN 2780 THEN 'Alqady Altnwkhy'
  WHEN 2781 THEN 'Abn Hndw'
  WHEN 2783 THEN 'Almamwn'
  WHEN 2785 THEN 'Abn Nbath Als''Dy'
  WHEN 2786 THEN 'Ibrahym Bn Almhdy'
  WHEN 2787 THEN 'Alsyd Alhmyry'
  WHEN 2788 THEN 'Khlf Alahmr'
  WHEN 2789 THEN 'Rby''H Alrqy'
  WHEN 2790 THEN 'Abw Alshys Alkhza''Y'
  WHEN 2791 THEN 'Abw Alhndy'
  WHEN 2793 THEN 'R''Bh Bn Al''Jaj'
  WHEN 2794 THEN '''Bdalsmd Al''Bdy'
  WHEN 2795 THEN 'Al''Many Alrajz'
  WHEN 2796 THEN 'Abn Babk'
  WHEN 2798 THEN 'Abw Hyh Alnmyry'
  WHEN 2799 THEN 'Alhsyn Bn Mtyr Alasdy'
  WHEN 2801 THEN 'Sa''D Albghdady'
  WHEN 2802 THEN '''Marh Bn ''Qyl'
  WHEN 2808 THEN 'Abw Bkr Alkhaldy'
  WHEN 2812 THEN 'Many Almwsws'
  WHEN 2813 THEN 'Khald Alkatb'
  WHEN 2815 THEN 'Abw Bkr Alswly'
  WHEN 2818 THEN 'Abn Hyws'
  WHEN 2819 THEN 'Almykaly'
  WHEN 2821 THEN 'Abn Qlaqs'
  WHEN 2823 THEN '''Marh Alymny'
  WHEN 2824 THEN 'Abn Hryq Alblnsy'
  WHEN 2826 THEN 'Mrj Alkhl'
  WHEN 2827 THEN 'Zafr Alhdad'
  WHEN 2828 THEN 'Abn Alsraj Almalqy'
  WHEN 2829 THEN 'Abn Hbysh'
  WHEN 2830 THEN 'Abn Alhnat'
  WHEN 2831 THEN 'Mrwan Altlyq'
  WHEN 2832 THEN 'Abn Aby Albshr'
  WHEN 2834 THEN 'Wladh Bnt Almstkfy'
  WHEN 2837 THEN 'Abn Hmdys'
  WHEN 2838 THEN 'Alabywrdy'
  WHEN 2839 THEN '''Bd Alghfar Alakhrs'
  WHEN 2840 THEN 'Alarjany'
  WHEN 2842 THEN 'Abw Alhsn Alshshtry'
  WHEN 2843 THEN 'Al''Fyf Altlmsany'
  WHEN 2844 THEN 'Abn Alhdad Alandlsy'
  WHEN 2845 THEN 'Abn Hdhyl Alqrtby'
  WHEN 2846 THEN 'Abn Hzm Alandlsy'
  WHEN 2847 THEN 'Abn Shhyd'
  WHEN 2848 THEN 'Abn Frkwn'
  WHEN 2849 THEN 'Abn Khatmh Alandlsy'
  WHEN 2850 THEN 'Ywsf Bn Harwn Alrmady'
  WHEN 2851 THEN 'Abn Aby Alkhsal'
  WHEN 2852 THEN 'Alttyly Ala''Ma'
  WHEN 2853 THEN 'Abw Hyan Alandlsy'
  WHEN 2854 THEN 'Sfwan Altjyby'
  WHEN 2855 THEN 'Abn Alsyd Albtlywsy'
  WHEN 2856 THEN 'Abn Han'' Alasghr'
  WHEN 2858 THEN 'Abn Bqy Alqrtby'
  WHEN 2860 THEN 'Abw Alwlyd Alhmyry'
  WHEN 2861 THEN 'Abw Bkr Bn Alqwtyh'
  WHEN 2863 THEN 'Alhys Bys'
  WHEN 2864 THEN 'Almlk Alamjd'
  WHEN 2865 THEN 'Alqady Alfadl'
  WHEN 2866 THEN 'Almkzwn Alsnjary'
  WHEN 2867 THEN 'Blbl Alghram Alhajry'
  WHEN 2870 THEN 'Allwah'
  WHEN 2882 THEN 'Abn Aljnan'
  WHEN 2885 THEN 'Abn Aldhan'
  WHEN 2886 THEN 'Abn Alsa''Aty'
  WHEN 2889 THEN 'Abn Almqrb Al''Ywny'
  WHEN 2894 THEN 'Abn Jbyr Alshatby'
  WHEN 2897 THEN 'Abn Dnynyr'
  WHEN 2904 THEN 'Abn Zhr Alhfyd'
  WHEN 2905 THEN 'Abn Sna'' Almlk'
  WHEN 2906 THEN 'Abn Salm Alhmdany'
  WHEN 2907 THEN 'Abn Shkyl'
  WHEN 2912 THEN 'Abn Tfyl'
  WHEN 2915 THEN 'Abn ''Nyn'
  WHEN 2916 THEN 'Abn Lbal Alshryshy'
  WHEN 2927 THEN 'Abw Alhsn Bn Hryq'
  WHEN 2928 THEN 'Abw Al''Bas Aljrawy'
  WHEN 2929 THEN 'Abw Alhsn Bn Khrwf'
  WHEN 2930 THEN 'Abw Alymn Alkndy'
  WHEN 2931 THEN 'Abw Almhasn Alshwa'''
  WHEN 2935 THEN 'Abw J''Fr Almlahy'
  WHEN 2936 THEN 'Asamh Bn Mnqdh'
  WHEN 2937 THEN 'Sbt Bn Alt''Awydhy'
  WHEN 2938 THEN 'Abw Mdyn Altlmsany'
  WHEN 2939 THEN 'Ftyan Alshaghwry'
  WHEN 2940 THEN 'Abw Zyd Alfazazy'
  WHEN 2942 THEN 'Alrsafy Alblnsy'
  WHEN 2943 THEN 'Kmal Aldyn Bn Alnbyh'
  WHEN 2944 THEN 'Dawd Bn ''Ysa Alaywby'
  WHEN 2945 THEN 'Mhyy Aldyn Bn ''Rby'
  WHEN 2946 THEN 'Alshrwrdy Almqtwl'
  WHEN 2948 THEN 'Alshhab Mhmwd Bn Slman'
  WHEN 2949 THEN 'Al''Mad Alasbhany'
  WHEN 2951 THEN '''Bd Almn''M Aljlyany'
  WHEN 2952 THEN 'Alshab Alzryf'
  WHEN 2953 THEN 'Alsraj Alwraq'
  WHEN 2956 THEN 'Abn Nbath Almsry'
  WHEN 2957 THEN 'Abn Hjr Al''Sqlany'
  WHEN 2958 THEN 'Abw Alhsyn Aljzar'
  WHEN 2960 THEN 'Shhab Aldyn Alkhlwf'
  WHEN 2961 THEN 'Mhmd Bn Hmyr Alhmdany'
  WHEN 2962 THEN 'Abn Aljyab Alghrnaty'
  WHEN 2965 THEN 'Abn Khlkan'
  WHEN 2970 THEN 'Abn Alabar Alblnsy'
  WHEN 2971 THEN 'Abn Alwrdy'
  WHEN 2974 THEN 'Albakhrzy'
  WHEN 2975 THEN 'Alshryf Almrtda'
  WHEN 2976 THEN 'Sfy Aldyn Alhly'
  WHEN 2977 THEN 'Bha'' Aldyn Zhyr'
  WHEN 2978 THEN 'Albr''Y'
  WHEN 2979 THEN 'Abn Alzqaq'
  WHEN 2980 THEN 'Tmym Alfatmy'
  WHEN 2981 THEN 'Alsrsry'
  WHEN 2983 THEN 'Abn Almuqry'
  WHEN 2984 THEN 'Alshryf Al''Qyly'
  WHEN 2986 THEN 'Abn Zmrk'
  WHEN 2990 THEN 'Slah Aldyn Alsfdy'
  WHEN 2991 THEN 'Abn Alkhyat'
  WHEN 2992 THEN 'Abn Shl Alandlsy'
  WHEN 2994 THEN 'Alzmkhshry'
  WHEN 2998 THEN '''Ly Alhsry Alqyrwany'
  WHEN 3001 THEN 'Abn Alqysrany'
  WHEN 3002 THEN 'Abn Qsym Alhmwy'
  WHEN 3003 THEN 'Abn Danyal Almwsly'
  WHEN 3004 THEN 'Abn Mnyr Altrablsy'
  WHEN 3005 THEN 'Alkhtyb Alhskfy'
  WHEN 3006 THEN 'Alshhab Almnswry'
  WHEN 3008 THEN 'Abn Alsbagh Aljdhamy'
  WHEN 3009 THEN 'Alstaly'
  WHEN 3011 THEN 'Abn Snan Alkhfajy'
  WHEN 3012 THEN 'Almhdhb Bn Alzbyr'
  WHEN 3013 THEN 'Shhab Aldyn Altl''Fry'
  WHEN 3014 THEN 'Alm''Tdd Bn ''Bad'
  WHEN 3015 THEN 'Abn Aby Hsynh'
  WHEN 3017 THEN 'Alnbhany Al''Many'
  WHEN 3019 THEN 'Abn Al''Dym'
  WHEN 3020 THEN 'Abw Bkr Al''Ydrws'
  WHEN 3021 THEN 'Abw Bkr Al''Nbry'
  WHEN 3022 THEN 'Abw Bhr Alkhty'
  WHEN 3023 THEN 'Alamyr Mnjk Basha'
  WHEN 3024 THEN 'Abn M''Twq'
  WHEN 3025 THEN 'Abn Razkh'
  WHEN 3026 THEN 'Abn Zakwr'
  WHEN 3027 THEN 'Abn Alnqyb'
  WHEN 3028 THEN 'Abn ''Lwy Alhdad'
  WHEN 3033 THEN 'Ywsf Alasyr Alhsyny'
  WHEN 3034 THEN 'Btrs Albstany'
  WHEN 3036 THEN 'Ibrahym Atymsh'
  WHEN 3038 THEN 'Ywsf Bn Aby Alfth'
  WHEN 3052 THEN 'Ywsf Albdy''Y'
  WHEN 3054 THEN 'Ibrahym Bn Yhya Al''Amly'
  WHEN 3056 THEN 'Hsn Hsny Altwyrany'
  WHEN 3058 THEN 'Alamyr Alsn''Any'
  WHEN 3060 THEN 'Abn Aljzry'
  WHEN 3062 THEN 'Abn M''Swm'
  WHEN 3063 THEN '''Bd Alghny Alnablsy'
  WHEN 3065 THEN 'Jmyl Sdqy Alzhawy'
  WHEN 3066 THEN 'Alhbl'
  WHEN 3067 THEN 'Ahmd Alkywany'
  WHEN 3068 THEN 'Mhmd Alm''Wly'
  WHEN 3070 THEN 'Nyqwlaws Alsa''Gh'
  WHEN 3072 THEN 'Alkydhawy'
  WHEN 3074 THEN 'Al''Ushary'
  WHEN 3076 THEN 'Abw Alm''Aly Altalwy'
  WHEN 3077 THEN 'Almhby'
  WHEN 3079 THEN 'Abn Altyb Alshrqy'
  WHEN 3080 THEN 'Bha'' Aldyn Al''Amly'
  WHEN 3082 THEN 'Ahmd Albhlwl'
  WHEN 3085 THEN 'Ahmd Bn Shahyn Alqbrsy'
  WHEN 3087 THEN 'Alwrghy'
  WHEN 3088 THEN '''Ly Alghrab Alsfaqsy'
  WHEN 3098 THEN 'Slamh Bn Jndl'
  WHEN 3105 THEN 'Wrqa'' Bn Zhyr'
  WHEN 3121 THEN 'Hnd Aldbabyh'
  WHEN 3127 THEN 'Hzylh Aljdysyh'
  WHEN 3130 THEN 'Hatm Alta''Y'
  WHEN 3134 THEN 'Aws Bn Hjr'
  WHEN 3139 THEN 'Abn Alr''La'''
  WHEN 3155 THEN 'Abw Alhkym Almry'
  WHEN 3182 THEN 'Asma'' Altghlbyh'
  WHEN 3196 THEN 'Alaswd Altghlby'
  WHEN 3217 THEN 'Aljyda'' Bnt Zahr Alzbydyh'
  WHEN 3219 THEN 'Alharth Aljrmy'
  WHEN 3221 THEN 'Alharth Bn ''Bad'
  WHEN 3223 THEN 'Alkhrnq Bnt Bdr'
  WHEN 3224 THEN 'Alkhnsa'' Bnt Altyjan'
  WHEN 3229 THEN 'Alhsyn Bn Hmam Alfzary'
  WHEN 3244 THEN 'Alsfah Altghlby'
  WHEN 3247 THEN 'Altfyl Alghnwy'
  WHEN 3260 THEN 'Almtlms Aldb''Y'
  WHEN 3261 THEN 'Almtnkhl'
  WHEN 3266 THEN 'Almthqb Al''Bdy'
  WHEN 3269 THEN 'Almrqsh Alasghr'
  WHEN 3271 THEN 'Almrqsh Alakbr'
  WHEN 3277 THEN 'Almmzq Al''Bdy'
  WHEN 3294 THEN 'Am Alaghr Bnt Rby''H Altghlbyh'
  WHEN 3297 THEN 'Amr'' Alqys Alzhyry'
  WHEN 3301 THEN 'Aamnh Bnt ''Tybh'
  WHEN 3313 THEN 'Bshr Bn Aby Khazm'
  WHEN 3325 THEN 'Tmadr Bnt Alshryd'
  WHEN 3334 THEN 'Jbr Alm''Awy'
  WHEN 3341 THEN '''Dy Bn Rby''H'
  WHEN 3342 THEN '''Lqmh Alfhl'
  WHEN 3344 THEN 'Dryd Bn Alsmh'
  WHEN 3350 THEN '''Mrw Bn Qmy''H'
  WHEN 3351 THEN 'Qs Bn Sa''Dh'
  WHEN 3353 THEN '''Dy Bn Zyd'
  WHEN 3366 THEN 'Hdbh Bn Alkhshrm'
  WHEN 3368 THEN '''Bd Allh Bn Alzbyr Alasdy'
  WHEN 3369 THEN 'Tryh Bn Isma''Yl Althqfy'
  WHEN 3378 THEN 'Hnd Bnt Aln''Man'
  WHEN 3382 THEN 'Alnahshaly'
  WHEN 3386 THEN 'Qys Bn Dhryh'
  WHEN 3387 THEN 'Almqn'' Alkndy'
  WHEN 3388 THEN 'Alahws Alansary'
  WHEN 3389 THEN 'Alkmyt Bn Zyd'
  WHEN 3390 THEN 'Yzyd Bn M''Awyh'
  WHEN 3391 THEN 'Alra''Y Alnmyry'
  WHEN 3395 THEN 'Wdah Alymn'
  WHEN 3396 THEN 'Nsyb Bn Rbah'
  WHEN 3397 THEN 'Kthyr ''Zh'
  WHEN 3399 THEN 'Al''Rjy'
  WHEN 3400 THEN 'Alhsyn Bn ''Ly'
  WHEN 3403 THEN 'Yzyd Bn Altthryh'
  WHEN 3404 THEN 'Mskyn Aldarmy'
  WHEN 3405 THEN 'Altrmah'
  WHEN 3406 THEN 'Qtry Bn Alfja''H'
  WHEN 3407 THEN '''Dy Bn Alrqa'''
  WHEN 3408 THEN 'Alqtal Alklaby'
  WHEN 3409 THEN 'Malk Bn Alryb'
  WHEN 3411 THEN 'Twbh Alkhfajy'
  WHEN 3413 THEN 'Abn Aldmynh'
  WHEN 3414 THEN 'Alnabghh Alshybany'
  WHEN 3418 THEN 'Lyla Alakhlylyh'
  WHEN 3419 THEN 'M''Awyh Bn Aby Sfyan'
  WHEN 3420 THEN '''Byd Allh Bn Alrqyat'
  WHEN 3421 THEN 'Sraqh Albarqy'
  WHEN 3425 THEN 'Swyd Bn Kra'''
  WHEN 3428 THEN 'Abw Dhbl Aljmhy'
  WHEN 3433 THEN 'Jran Al''Wd Alnmry'
  WHEN 3434 THEN '''Bydh Alyshkry'
  WHEN 3436 THEN 'Almtwkl Allythy'
  WHEN 3439 THEN '''Mr Bn Lja Altymy'
  WHEN 3440 THEN 'Al''Jyr Alslwly'
  WHEN 3446 THEN 'A''Sha Hmdan'
  WHEN 3447 THEN 'Abw Alnjm Al''Jly'
  WHEN 3449 THEN 'Abw Skhr Alhdhly'
  WHEN 3453 THEN 'Mhmd Bn Bshyr Alkharjy'
  WHEN 3455 THEN 'Abw Altfyl Alqrshy'
  WHEN 3456 THEN 'Zyadh Bn Zyd Al''Dhry'
  WHEN 3458 THEN 'Abw Zbyd Alta''Y'
  WHEN 3460 THEN 'Abw Wjzh Als''Dy'
  WHEN 3461 THEN '''Byd Bn Aywb Al''Nbry'
  WHEN 3463 THEN '''Byd Allh Alja''Fy'
  WHEN 3466 THEN 'Nhshl Bn Hry'
  WHEN 3470 THEN '''Bd Allh Bn Alzb''Ra'
  WHEN 3471 THEN 'Hmyd Bn Thwr Alhlaly'
  WHEN 3473 THEN 'Far''H Almryh'
  WHEN 3478 THEN 'Abw Talb'
  WHEN 3483 THEN 'Alnabghh Alj''Dy'
  WHEN 3486 THEN 'Abw Bkr Alsdyq'
  WHEN 3487 THEN 'Malk Alashtr'
  WHEN 3489 THEN 'Abw Dh''Yb Alhdhly'
  WHEN 3491 THEN 'Al''Jaj'
  WHEN 3492 THEN 'Alshmakh Aldhbyany'
  WHEN 3493 THEN 'Al''Bas Bn Mrdas'
  WHEN 3495 THEN 'Drar Alfhry'
  WHEN 3496 THEN 'Amyh Bn Aby Alslt'
  WHEN 3498 THEN '''Mrw Albahly'
  WHEN 3499 THEN '''Mrw Bn M''D Ykrb'
  WHEN 3500 THEN 'Hnd Bnt ''Tbh'
  WHEN 3501 THEN 'Abw Mhjn Althqfy'
  WHEN 3502 THEN 'Alnmr Bn Twlb'
  WHEN 3503 THEN 'Naf'' Bn Alaswd'
  WHEN 3505 THEN 'Tmym Bn Aby Bn Mqbl'
  WHEN 3506 THEN 'Qys Bn Alkhtym'
  WHEN 3507 THEN 'K''B Bn Malk Alansary'
  WHEN 3509 THEN '''Bd Allh Bn Rwahh'
  WHEN 3510 THEN 'Alhadrh'
  WHEN 3511 THEN 'Khrash Alhdhly'
  WHEN 3513 THEN 'Mtmm Alyrbw''Y'
  WHEN 3515 THEN '''Mrw Bn Alahtm'
  WHEN 3516 THEN 'Alzbrqan Bn Bdr'
  WHEN 3517 THEN '''Amr Bn Altfyl'
  WHEN 3518 THEN 'M''N Almzny'
  WHEN 3527 THEN '''Mar Bn Yasr'
  WHEN 3529 THEN 'Alnjashy Alharthy'
  WHEN 3532 THEN 'Mhmwd Samy Albarwdy'
  WHEN 3533 THEN 'Mstfa Sadq Alraf''Y'
  WHEN 3536 THEN '''Bas Mhmwd Al''Qad'
  WHEN 3538 THEN 'Ibrahym ''Bd Alqadr Almazny'
END
WHERE id IN (
  3,
  4,
  5,
  6,
  7,
  8,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  32,
  33,
  34,
  35,
  36,
  37,
  39,
  40,
  41,
  42,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  76,
  77,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  218,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  300,
  301,
  302,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  318,
  319,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  375,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384,
  385,
  386,
  387,
  388,
  389,
  390,
  391,
  392,
  393,
  394,
  395,
  396,
  397,
  398,
  399,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  436,
  437,
  438,
  439,
  440,
  441,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  456,
  457,
  458,
  459,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499,
  500,
  501,
  502,
  503,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  513,
  514,
  515,
  516,
  517,
  518,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550,
  551,
  552,
  553,
  554,
  555,
  556,
  557,
  558,
  559,
  560,
  561,
  562,
  563,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  2611,
  2621,
  2631,
  2632,
  2635,
  2636,
  2637,
  2638,
  2639,
  2645,
  2648,
  2655,
  2656,
  2660,
  2664,
  2665,
  2666,
  2673,
  2674,
  2678,
  2681,
  2684,
  2689,
  2690,
  2697,
  2698,
  2699,
  2703,
  2706,
  2707,
  2708,
  2709,
  2714,
  2716,
  2717,
  2718,
  2719,
  2720,
  2721,
  2722,
  2724,
  2725,
  2726,
  2727,
  2728,
  2729,
  2730,
  2731,
  2732,
  2733,
  2734,
  2735,
  2736,
  2741,
  2742,
  2743,
  2744,
  2745,
  2746,
  2748,
  2751,
  2752,
  2753,
  2754,
  2755,
  2756,
  2758,
  2759,
  2761,
  2762,
  2764,
  2765,
  2766,
  2767,
  2769,
  2771,
  2772,
  2773,
  2774,
  2775,
  2776,
  2778,
  2780,
  2781,
  2783,
  2785,
  2786,
  2787,
  2788,
  2789,
  2790,
  2791,
  2793,
  2794,
  2795,
  2796,
  2798,
  2799,
  2801,
  2802,
  2808,
  2812,
  2813,
  2815,
  2818,
  2819,
  2821,
  2823,
  2824,
  2826,
  2827,
  2828,
  2829,
  2830,
  2831,
  2832,
  2834,
  2837,
  2838,
  2839,
  2840,
  2842,
  2843,
  2844,
  2845,
  2846,
  2847,
  2848,
  2849,
  2850,
  2851,
  2852,
  2853,
  2854,
  2855,
  2856,
  2858,
  2860,
  2861,
  2863,
  2864,
  2865,
  2866,
  2867,
  2870,
  2882,
  2885,
  2886,
  2889,
  2894,
  2897,
  2904,
  2905,
  2906,
  2907,
  2912,
  2915,
  2916,
  2927,
  2928,
  2929,
  2930,
  2931,
  2935,
  2936,
  2937,
  2938,
  2939,
  2940,
  2942,
  2943,
  2944,
  2945,
  2946,
  2948,
  2949,
  2951,
  2952,
  2953,
  2956,
  2957,
  2958,
  2960,
  2961,
  2962,
  2965,
  2970,
  2971,
  2974,
  2975,
  2976,
  2977,
  2978,
  2979,
  2980,
  2981,
  2983,
  2984,
  2986,
  2990,
  2991,
  2992,
  2994,
  2998,
  3001,
  3002,
  3003,
  3004,
  3005,
  3006,
  3008,
  3009,
  3011,
  3012,
  3013,
  3014,
  3015,
  3017,
  3019,
  3020,
  3021,
  3022,
  3023,
  3024,
  3025,
  3026,
  3027,
  3028,
  3033,
  3034,
  3036,
  3038,
  3052,
  3054,
  3056,
  3058,
  3060,
  3062,
  3063,
  3065,
  3066,
  3067,
  3068,
  3070,
  3072,
  3074,
  3076,
  3077,
  3079,
  3080,
  3082,
  3085,
  3087,
  3088,
  3098,
  3105,
  3121,
  3127,
  3130,
  3134,
  3139,
  3155,
  3182,
  3196,
  3217,
  3219,
  3221,
  3223,
  3224,
  3229,
  3244,
  3247,
  3260,
  3261,
  3266,
  3269,
  3271,
  3277,
  3294,
  3297,
  3301,
  3313,
  3325,
  3334,
  3341,
  3342,
  3344,
  3350,
  3351,
  3353,
  3366,
  3368,
  3369,
  3378,
  3382,
  3386,
  3387,
  3388,
  3389,
  3390,
  3391,
  3395,
  3396,
  3397,
  3399,
  3400,
  3403,
  3404,
  3405,
  3406,
  3407,
  3408,
  3409,
  3411,
  3413,
  3414,
  3418,
  3419,
  3420,
  3421,
  3425,
  3428,
  3433,
  3434,
  3436,
  3439,
  3440,
  3446,
  3447,
  3449,
  3453,
  3455,
  3456,
  3458,
  3460,
  3461,
  3463,
  3466,
  3470,
  3471,
  3473,
  3478,
  3483,
  3486,
  3487,
  3489,
  3491,
  3492,
  3493,
  3495,
  3496,
  3498,
  3499,
  3500,
  3501,
  3502,
  3503,
  3505,
  3506,
  3507,
  3509,
  3510,
  3511,
  3513,
  3515,
  3516,
  3517,
  3518,
  3527,
  3529,
  3532,
  3533,
  3536,
  3538
)
  AND name_en IS NULL;
