-- Add English name column to poets table for bilingual display
ALTER TABLE public.poets ADD COLUMN IF NOT EXISTS name_en TEXT;

-- Populate English names for known poets
-- This covers the major classical and modern Arabic poets in the database
UPDATE public.poets SET name_en = CASE name
  WHEN 'المتنبي' THEN 'Al-Mutanabbi'
  WHEN 'محمود درويش' THEN 'Mahmoud Darwish'
  WHEN 'نزار قباني' THEN 'Nizar Qabbani'
  WHEN 'أبو العلاء المعري' THEN 'Al-Ma''arri'
  WHEN 'عنترة بن شداد' THEN 'Antarah ibn Shaddad'
  WHEN 'أبو الطيب المتنبي' THEN 'Al-Mutanabbi'
  WHEN 'امرؤ القيس' THEN 'Imru'' al-Qais'
  WHEN 'أبو نواس' THEN 'Abu Nuwas'
  WHEN 'أبو تمام' THEN 'Abu Tammam'
  WHEN 'البحتري' THEN 'Al-Buhturi'
  WHEN 'أبو فراس الحمداني' THEN 'Abu Firas al-Hamdani'
  WHEN 'الشريف الرضي' THEN 'Al-Sharif al-Radi'
  WHEN 'ابن زيدون' THEN 'Ibn Zaydun'
  WHEN 'المعتمد بن عباد' THEN 'Al-Mu''tamid ibn Abbad'
  WHEN 'أبو العتاهية' THEN 'Abu al-Atahiya'
  WHEN 'الأخطل' THEN 'Al-Akhtal'
  WHEN 'جرير' THEN 'Jarir'
  WHEN 'الفرزدق' THEN 'Al-Farazdaq'
  WHEN 'أبو البقاء الرندي' THEN 'Abu al-Baqa al-Rundi'
  WHEN 'أبو الأسود الدؤلي' THEN 'Abu al-Aswad al-Du''ali'
  WHEN 'أبو إسحاق الإلبيري' THEN 'Abu Ishaq al-Ilbiri'
  WHEN 'أبو الطمحان القيني' THEN 'Abu al-Tamhan al-Qayni'
  WHEN 'بدر شاكر السياب' THEN 'Badr Shakir al-Sayyab'
  WHEN 'أحمد شوقي' THEN 'Ahmad Shawqi'
  WHEN 'حافظ إبراهيم' THEN 'Hafiz Ibrahim'
  WHEN 'إيليا أبو ماضي' THEN 'Elia Abu Madi'
  WHEN 'جبران خليل جبران' THEN 'Khalil Gibran'
  WHEN 'أدونيس' THEN 'Adonis'
  WHEN 'سميح القاسم' THEN 'Samih al-Qasim'
  WHEN 'فدوى طوقان' THEN 'Fadwa Tuqan'
  WHEN 'غادة السمان' THEN 'Ghada al-Samman'
  WHEN 'أمل دنقل' THEN 'Amal Dunqul'
  WHEN 'صلاح عبد الصبور' THEN 'Salah Abd al-Sabur'
  WHEN 'عبد الرحمن الأبنودي' THEN 'Abdel Rahman el-Abnudi'
  WHEN 'أحمد مطر' THEN 'Ahmad Matar'
  WHEN 'محمد الماغوط' THEN 'Muhammad al-Maghut'
  WHEN 'الخنساء' THEN 'Al-Khansa'
  WHEN 'ابن الرومي' THEN 'Ibn al-Rumi'
  WHEN 'ابن الفارض' THEN 'Ibn al-Farid'
  WHEN 'المهلهل بن ربيعة' THEN 'Al-Muhalhil'
  WHEN 'طرفة بن العبد' THEN 'Tarafa ibn al-Abd'
  WHEN 'زهير بن أبي سلمى' THEN 'Zuhayr ibn Abi Sulma'
  WHEN 'لبيد بن ربيعة' THEN 'Labid ibn Rabi''a'
  WHEN 'عمرو بن كلثوم' THEN 'Amr ibn Kulthum'
  WHEN 'الحارث بن حلزة' THEN 'Al-Harith ibn Hilliza'
  WHEN 'النابغة الذبياني' THEN 'Al-Nabigha al-Dhubyani'
  WHEN 'حسان بن ثابت' THEN 'Hassan ibn Thabit'
  WHEN 'كعب بن زهير' THEN 'Ka''b ibn Zuhayr'
  WHEN 'الأعشى' THEN 'Al-A''sha'
  WHEN 'ذو الرمة' THEN 'Dhu al-Rumma'
  WHEN 'بشار بن برد' THEN 'Bashshar ibn Burd'
  WHEN 'ابن المقفع' THEN 'Ibn al-Muqaffa'
  WHEN 'الجاحظ' THEN 'Al-Jahiz'
  WHEN 'المنفلوطي' THEN 'Al-Manfaluti'
  WHEN 'معروف الرصافي' THEN 'Ma''ruf al-Rusafi'
  WHEN 'إبراهيم ناجي' THEN 'Ibrahim Naji'
  WHEN 'عمر أبو ريشة' THEN 'Omar Abu Risha'
  WHEN 'ميخائيل نعيمة' THEN 'Mikha''il Na''ima'
  WHEN 'أبو القاسم الشابي' THEN 'Abu al-Qasim al-Shabbi'
  WHEN 'بلند الحيدري' THEN 'Buland al-Haidari'
  WHEN 'عبد الوهاب البياتي' THEN 'Abd al-Wahhab al-Bayati'
  WHEN 'نازك الملائكة' THEN 'Nazik al-Mala''ika'
  WHEN 'توفيق زياد' THEN 'Tawfiq Zayyad'
  WHEN 'مظفر النواب' THEN 'Muzaffar al-Nawab'
  ELSE name
END
WHERE name_en IS NULL;

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_poets_name_en ON public.poets (name_en) WHERE name_en IS NOT NULL;
