-- Backfill poet life dates, then derive century from them.
--
-- Phase 2/3 of #721. The reviewed mapping this is generated from lives at
-- docs/data/poet-dates.csv (human-readable) and docs/data/poet-dates.json
-- (machine-readable, the direct input to this file). Regenerate rather than
-- hand-edit: the CSV is the thing that was reviewed.
--
-- 702 of 711 poets get dates. The remaining 9 keep NULL on all
-- three year columns and therefore a NULL century, which every API path already
-- handles (undated=1 / includeUndated=1):
--   مجهول — Anonymous corpus entry - see spot-check note; not datable
--   يحيى الحمادي — No reliable dates found
--   شهاب الدين ابن دمرداش — No reliable dates found
--   وصف المطر والسحاب — NOT A POET - theme label ("description of rain and clouds") misfiled as a poet row
--   الفروسية — NOT A POET - theme label ("chivalry") misfiled as a poet row
--   ابن النقيب — Ambiguous nisba; no reliable dates
--   شعراء مجهولون — Anonymous corpus entry - see spot-check note; not datable
--   ثورات التغيير العربية — NOT A POET - theme label ("Arab uprisings") misfiled as a poet row
--   المدايح النبوية — NOT A POET - theme label ("prophetic panegyric") misfiled as a poet row
--
-- date_confidence is 'exact' for 302 poets and 'approx' for 400.
-- 'approx' covers three cases, all spelled out per row in the CSV's source_note:
-- attested-but-disputed years, a floruit estimate where no death year survives,
-- and boundary poets pulled a few years to stay with the era they belong to
-- (Antara, al-Nabigha, Zuhayr, al-Tufayl, Qays ibn al-Khatim, Aws ibn Hajr all
-- died c.600-620 — ordinally the 7th century, literarily the Jahiliyya).

-- Explicit transaction: the poets UPDATE and the poems.century recompute below
-- are one change. Aborting between them would leave poets dated and
-- poems.century still carrying the old era stamps. Do not rely on the migration
-- runner to wrap it.
BEGIN;

WITH b (name, death_year, birth_year, active_year, date_confidence) AS (
  VALUES
  ('أبو العلاء المعري'::text, 1057::smallint, 973::smallint, NULL::smallint, 'exact'::public.poet_date_confidence),
  ('ابن الرومي', 896, 836, NULL, 'exact'),
  ('المتنبي', 965, 915, NULL, 'exact'),
  ('أبو نواس', 814, 756, NULL, 'approx'),
  ('الإمام الشافعي', 820, 767, NULL, 'exact'),
  ('العباس بن الأحنف', 808, 750, NULL, 'approx'),
  ('ابن المعتز', 908, 861, NULL, 'exact'),
  ('الخنساء', 645, 575, NULL, 'approx'),
  ('صفي الدين الحلي', 1349, 1278, NULL, 'exact'),
  ('أبو فراس الحمداني', 968, 932, NULL, 'exact'),
  ('أسامة بن منقذ', 1188, 1095, NULL, 'exact'),
  ('ابن خفاجة', 1139, 1058, NULL, 'exact'),
  ('أبو تمام', 845, 805, NULL, 'approx'),
  ('علي بن أبي طالب', 661, 601, NULL, 'exact'),
  ('الحلاج', 922, 858, NULL, 'exact'),
  ('لسان الدين بن الخطيب', 1374, 1313, NULL, 'exact'),
  ('أحمد شوقي', 1932, 1868, NULL, 'exact'),
  ('ابن حمديس', 1133, 1055, NULL, 'exact'),
  ('محيي الدين بن عربي', 1240, 1165, NULL, 'exact'),
  ('محمود سامي البارودي', 1904, 1839, NULL, 'exact'),
  ('الشريف الرضي', 1015, 970, NULL, 'exact'),
  ('أبو العتاهية', 826, 748, NULL, 'exact'),
  ('قيس بن الملوح', 688, NULL, NULL, 'approx'),
  ('ابن زيدون', 1071, 1003, NULL, 'exact'),
  ('المعتمد بن عباد', 1095, 1040, NULL, 'exact'),
  ('قيس بن الملوح (مجنون ليلى )', 688, NULL, NULL, 'approx'),
  ('البحتري', 897, 821, NULL, 'exact'),
  ('كشاجم', 971, NULL, NULL, 'approx'),
  ('الطغرائي', 1121, 1061, NULL, 'exact'),
  ('الفرزدق', 728, 641, NULL, 'approx'),
  ('الوأواء الدمشقي', 995, NULL, NULL, 'approx'),
  ('عمر بن أبي ربيعة', 712, 644, NULL, 'approx'),
  ('عنترة بن شداد', 600, NULL, NULL, 'approx'),
  ('ابن عبد ربه', 940, 860, NULL, 'exact'),
  ('الشريف المرتضى', 1044, 966, NULL, 'exact'),
  ('ابن الفارض', 1235, 1181, NULL, 'exact'),
  ('بشار بن برد', 784, 714, NULL, 'exact'),
  ('ابن عبد ربه الاندلسي', 940, 860, NULL, 'exact'),
  ('النابغة الذبياني', 600, NULL, NULL, 'approx'),
  ('ديك الجن', 849, 777, NULL, 'approx'),
  ('محمود درويش', 2008, 1941, NULL, 'exact'),
  ('ذو الرمة', 735, 696, NULL, 'exact'),
  ('قيس بن ذريح', 688, NULL, NULL, 'approx'),
  ('كثير عزة', 723, NULL, NULL, 'exact'),
  ('الامام علي بن ابي طالب', 661, 601, NULL, 'exact'),
  ('ابن نباتة المصري', 1366, 1287, NULL, 'exact'),
  ('بهاء الدين زهير', 1258, 1186, NULL, 'exact'),
  ('إيليا أبو ماضي', 1957, 1889, NULL, 'exact'),
  ('أبو الفتح البستي', 1010, NULL, NULL, 'approx'),
  ('الأبيوردي', 1113, NULL, NULL, 'exact'),
  ('جبران خليل جبران', 1931, 1883, NULL, 'exact'),
  ('دعبل الخزاعي', 860, 765, NULL, 'exact'),
  ('عباس محمود العقاد', 1964, 1889, NULL, 'exact'),
  ('ابن حزم الأندلسي', 1064, 994, NULL, 'exact'),
  ('ابن سهل الأندلسي', 1251, 1212, NULL, 'exact'),
  ('خليل مطران', 1949, 1872, NULL, 'exact'),
  ('قيس بن الملوح (مجنون ليلى)', 688, NULL, NULL, 'approx'),
  ('ابراهيم ناجي', 1953, 1898, NULL, 'exact'),
  ('احمد الصافي النجفي', 1977, 1897, NULL, 'exact'),
  ('امرؤ القيس', 540, NULL, NULL, 'approx'),
  ('نزار قباني', 1998, 1923, NULL, 'exact'),
  ('ابن رشيق القيرواني', 1063, 1000, NULL, 'approx'),
  ('جرير', 728, 653, NULL, 'approx'),
  ('حسان بن ثابت', 674, NULL, NULL, 'approx'),
  ('لبيد بن ربيعة', 661, NULL, NULL, 'approx'),
  ('ابو القاسم الشابي', 1934, 1909, NULL, 'exact'),
  ('مصطفى صادق الرافعي', 1937, 1880, NULL, 'exact'),
  ('ابن الزقاق البلنسي', 1134, 1096, NULL, 'approx'),
  ('ابو بكر الصنوبري', 945, NULL, NULL, 'exact'),
  ('ابن سناء الملك', 1211, 1155, NULL, 'exact'),
  ('حافظ ابراهيم', 1932, 1872, NULL, 'exact'),
  ('عبد الله بن المبارك', 797, 726, NULL, 'exact'),
  ('أبو حيان الأندلسي', 1344, 1256, NULL, 'exact'),
  ('جميل بثينة', 701, NULL, NULL, 'exact'),
  ('طرفة بن العبد', 564, NULL, NULL, 'approx'),
  ('احمد مطر', NULL, 1954, 1990, 'exact'),
  ('ابن الساعاتي', 1207, 1153, NULL, 'exact'),
  ('أبو الحسن الجرجاني', 1001, NULL, NULL, 'exact'),
  ('ابن الوردي', 1349, 1292, NULL, 'exact'),
  ('ابو حيان النحوي الاندلسي', 1344, 1256, NULL, 'exact'),
  ('ادونيس', NULL, 1930, 1975, 'exact'),
  ('ابن معصوم المدني', 1707, 1642, NULL, 'exact'),
  ('محي الدين بن عربي', 1240, 1165, NULL, 'exact'),
  ('الرصافي البلنسي', 1177, NULL, NULL, 'approx'),
  ('ابن الدمينة', 747, NULL, NULL, 'approx'),
  ('ابن خاتمة الأندلسي', 1369, NULL, NULL, 'exact'),
  ('ابن دريد الأزدي', 933, 837, NULL, 'exact'),
  ('ابن سعيد المغربي', 1286, 1213, NULL, 'exact'),
  ('العفيف التلمساني', 1291, 1213, NULL, 'exact'),
  ('زهير بن أبي سلمى', 600, NULL, NULL, 'approx'),
  ('عبد الغني النابلسي', 1731, 1641, NULL, 'exact'),
  ('الحكم بن ابي الصلت', 1134, NULL, NULL, 'exact'),
  ('السري الرفاء', 973, NULL, NULL, 'approx'),
  ('السيد الحميري', 789, 723, NULL, 'approx'),
  ('امية الداني ( الحكم بن ابي الصلت )', 1134, NULL, NULL, 'exact'),
  ('عبد الله بن رواحة', 629, NULL, NULL, 'exact'),
  ('عمرو بن كلثوم', 584, NULL, NULL, 'approx'),
  ('ابن عنين', 1233, 1154, NULL, 'exact'),
  ('الشافعي', 820, 767, NULL, 'exact'),
  ('محمد مهدي الجواهري', 1997, 1899, NULL, 'exact'),
  ('أبو الأسود الدؤلي', 688, 603, NULL, 'exact'),
  ('أبو هلال العسكري', 1005, NULL, NULL, 'approx'),
  ('الحطيئة', 670, NULL, NULL, 'approx'),
  ('الصنوبري', 945, NULL, NULL, 'exact'),
  ('علي الحصري القيرواني', 1095, 1029, NULL, 'exact'),
  ('علية بنت المهدي', 825, 777, NULL, 'exact'),
  ('ابن زاكور', 1731, 1665, NULL, 'exact'),
  ('ابن معصوم الحسني الحسيني', 1707, 1642, NULL, 'exact'),
  ('ابو الفضل بن الاحنف', 808, 750, NULL, 'approx'),
  ('ابو الربيع سليمان الموحدي', NULL, NULL, 1200, 'approx'),
  ('محمود المشهداني', NULL, NULL, 2010, 'approx'),
  ('إبراهيم بن هرمة', 792, 709, NULL, 'approx'),
  ('ابن دراج القسطلي', 1030, 958, NULL, 'exact'),
  ('ابن شهيد', 1035, 992, NULL, 'exact'),
  ('ابن طباطبا العلوي', 934, NULL, NULL, 'exact'),
  ('ابن هانئ الأصغر', 1179, NULL, NULL, 'approx'),
  ('الأحوص الأنصاري', 723, NULL, NULL, 'approx'),
  ('الراعي النميري', 708, NULL, NULL, 'approx'),
  ('الصاحب بن عباد', 995, 938, NULL, 'exact'),
  ('تأبط شرا', 530, NULL, NULL, 'approx'),
  ('حاتم الطائي', 578, NULL, NULL, 'approx'),
  ('عدي بن الرقاع', 714, NULL, NULL, 'approx'),
  ('عدي بن زيد', 600, NULL, NULL, 'approx'),
  ('محمود الوراق', 845, NULL, NULL, 'approx'),
  ('ولادة بنت المستكفي', 1091, 1001, NULL, 'exact'),
  ('علي محمود طه', 1949, 1901, NULL, 'exact'),
  ('ابراهيم طوقان', 1941, 1905, NULL, 'exact'),
  ('أبو مدين التلمساني', 1198, 1126, NULL, 'exact'),
  ('معروف الرصافي', 1945, 1875, NULL, 'exact'),
  ('عبد الجبار بن حمديس', 1133, 1055, NULL, 'exact'),
  ('عمر ابن ابي ربيعة', 712, 644, NULL, 'approx'),
  ('ابن الحداد الأندلسي', 1087, NULL, NULL, 'approx'),
  ('ابن نباتة السعدي', 1015, 938, NULL, 'exact'),
  ('ابن هانئ الأندلسي', 973, 934, NULL, 'exact'),
  ('ابو بكر الخالدي ( الخالديان )', 990, NULL, NULL, 'approx'),
  ('الخبز أرزي', 938, NULL, NULL, 'approx'),
  ('خالد الكاتب', 876, NULL, NULL, 'approx'),
  ('محمد بن حازم الباهلي', 874, NULL, NULL, 'approx'),
  ('الأمير الصنعاني', 1768, 1688, NULL, 'exact'),
  ('جميل صدقي الزهاوي', 1936, 1863, NULL, 'exact'),
  ('ريم سليمان الخش', NULL, NULL, 2010, 'approx'),
  ('صالح طه ( ظميان غدير )', NULL, NULL, 2010, 'approx'),
  ('غيداء الايوبي', NULL, NULL, 2010, 'approx'),
  ('القاضي الفاضل', 1200, 1135, NULL, 'exact'),
  ('أبو الحسن الششتري', 1269, 1212, NULL, 'exact'),
  ('أبو بكر الشبلي', 946, 861, NULL, 'exact'),
  ('أبو دهبل الجمحي', 715, NULL, NULL, 'approx'),
  ('ابن القيسراني', 1154, 1085, NULL, 'exact'),
  ('ابن سارة ( صارة ) الشنتريني', 1123, NULL, NULL, 'exact'),
  ('ابن سنان الخفاجي', 1073, 1032, NULL, 'exact'),
  ('ابن وكيع التنيسي', 1003, NULL, NULL, 'exact'),
  ('جميل بن معمر', 701, NULL, NULL, 'exact'),
  ('شهاب الدين التلعفري', 1277, 1194, NULL, 'exact'),
  ('عدي بن ربيعة المهلهل ( الزير )', 531, NULL, NULL, 'approx'),
  ('علي بن الجهم', 863, 804, NULL, 'exact'),
  ('عمارة اليمني', 1174, 1121, NULL, 'exact'),
  ('مالك بن الريب', 680, NULL, NULL, 'approx'),
  ('مهيار الديلمي', 1037, NULL, NULL, 'exact'),
  ('نصيب بن رباح', 726, NULL, NULL, 'approx'),
  ('أبو بحر الخطي', 1618, 1554, NULL, 'approx'),
  ('ابن معصوم', 1707, 1642, NULL, 'exact'),
  ('محمد العيد ال خليفة', 1979, 1904, NULL, 'exact'),
  ('غازي القصيبي', 2010, 1940, NULL, 'exact'),
  ('أبو زيد الفازازي', 1230, NULL, NULL, 'exact'),
  ('ابو الفضل الوليد', 1941, 1886, NULL, 'exact'),
  ('قيس لبنى', 688, NULL, NULL, 'approx'),
  ('ابن رشيق القيرواني الازدي', 1063, 1000, NULL, 'approx'),
  ('أبو ذؤيب الهذلي', 649, NULL, NULL, 'approx'),
  ('أبو طالب', 619, 539, NULL, 'approx'),
  ('ابن الهبارية', 1115, 1023, NULL, 'exact'),
  ('ابن داود الظاهري', 910, 868, NULL, 'exact'),
  ('ابن ميادة', 764, NULL, NULL, 'approx'),
  ('اسحاق الموصلي', 850, 767, NULL, 'exact'),
  ('الأحنف العكبري', 1015, NULL, NULL, 'approx'),
  ('الباخرزي', 1075, NULL, NULL, 'exact'),
  ('الثعالبي', 1038, 961, NULL, 'exact'),
  ('المتلمس الضبعي', 580, NULL, NULL, 'approx'),
  ('صاعد البغدادي', 1026, NULL, NULL, 'approx'),
  ('صلاح الدين الصفدي', 1363, 1296, NULL, 'exact'),
  ('عامر بن الطفيل', 630, NULL, NULL, 'approx'),
  ('كعب بن زهير', 645, NULL, NULL, 'approx'),
  ('وجيه الدولة الحمداني', 1000, NULL, NULL, 'approx'),
  ('يوسف بن هارون الرمادي', 1013, NULL, NULL, 'exact'),
  ('مجنون ليلى', 688, NULL, NULL, 'approx'),
  ('ابن دريد', 933, 837, NULL, 'exact'),
  ('زيد بن عمرو بن نفيل', 605, NULL, NULL, 'approx'),
  ('عبدالله البردوني', 1999, 1929, NULL, 'exact'),
  ('ابن مقبل', 670, NULL, NULL, 'approx'),
  ('السهروردي المقتول', 1191, 1154, NULL, 'exact'),
  ('الحيص بيص', 1179, 1096, NULL, 'exact'),
  ('عدنان الصايغ', NULL, 1955, 1995, 'exact'),
  ('يعقوب بن علي ال ابراهيم', NULL, NULL, 1950, 'approx'),
  ('ابن لبال الشريشي', 1187, 1116, NULL, 'exact'),
  ('ابو اسحاق الصابي', 994, 925, NULL, 'exact'),
  ('المفتي فتح الله', NULL, NULL, 1600, 'approx'),
  ('امل دنقل', 1983, 1940, NULL, 'exact'),
  ('علي الجارم', 1949, 1881, NULL, 'exact'),
  ('ابو الفضل بن العميد', 970, NULL, NULL, 'exact'),
  ('حيدر الحلي', 1886, 1831, NULL, 'exact'),
  ('سبط ابن التعاويذي', 1188, 1126, NULL, 'exact'),
  ('ماء العينين', 1910, 1830, NULL, 'exact'),
  ('ابن عطية الاندلسي', 1147, 1088, NULL, 'exact'),
  ('أبو إسحاق الإلبيري', 1067, NULL, NULL, 'exact'),
  ('أبو البقاء الرندي', 1285, 1204, NULL, 'exact'),
  ('ابن الجياب الغرناطي', 1349, 1274, NULL, 'exact'),
  ('ابن الحاج النميري', 1383, 1315, NULL, 'approx'),
  ('ابن السيد البطليوسي', 1127, 1052, NULL, 'exact'),
  ('ابن حديدة اللخمي القيرواني', NULL, NULL, 1100, 'approx'),
  ('ابن شرف القيرواني', 1068, 1000, NULL, 'exact'),
  ('ابن هذيل القرطبي', NULL, NULL, 1200, 'approx'),
  ('ابو جعفر بن سعيد الاندلسي', 1163, NULL, NULL, 'approx'),
  ('ابو عثمان الخالدي ( الخالديان )', 980, NULL, NULL, 'approx'),
  ('الاخيطل الاحوازي', NULL, NULL, 900, 'approx'),
  ('التهامي', 1025, NULL, NULL, 'exact'),
  ('الحارث بن حلزة', 570, NULL, NULL, 'approx'),
  ('الشاب الظريف', 1289, 1263, NULL, 'exact'),
  ('القاضي التنوخي', 994, 940, NULL, 'exact'),
  ('القاضي عبد الوهاب المالكي', 1031, 973, NULL, 'exact'),
  ('جحظة البرمكي', 938, 839, NULL, 'exact'),
  ('ذو النون المصري', 861, 796, NULL, 'exact'),
  ('عبد الرحمن الداخل', 788, 731, NULL, 'exact'),
  ('عبيد الله بن الرقيات', 704, NULL, NULL, 'approx'),
  ('عرقلة الدمشقي', 1171, 1106, NULL, 'exact'),
  ('عروة بن الورد', 594, NULL, NULL, 'approx'),
  ('عماد الدين الاصفهاني', 1201, 1125, NULL, 'exact'),
  ('عمار بن ياسر', 657, 566, NULL, 'approx'),
  ('عمرو بن معد يكرب', 642, NULL, NULL, 'approx'),
  ('يزيد بن معاوية', 683, 647, NULL, 'exact'),
  ('ابن الجزري', 1429, 1350, NULL, 'exact'),
  ('ابن معتوق', 1676, 1616, NULL, 'exact'),
  ('حسن حسني الطويراني', 1897, 1850, NULL, 'exact'),
  ('ابن هتيمل', 1350, NULL, NULL, 'approx'),
  ('احسان البني', NULL, NULL, 1980, 'approx'),
  ('توفيق زياد', 1994, 1929, NULL, 'exact'),
  ('ابن زهر الحفيد', 1198, 1113, NULL, 'exact'),
  ('ابن نما الحلي', 1287, 1222, NULL, 'exact'),
  ('العماد الأصبهاني', 1201, 1125, NULL, 'exact'),
  ('ابراهيم اليازجي', 1906, 1847, NULL, 'exact'),
  ('ابن النبيه', 1222, NULL, NULL, 'exact'),
  ('المكزون السنجاري', 1240, 1188, NULL, 'exact'),
  ('بلبل الغرام الحاجري', 1235, 1185, NULL, 'approx'),
  ('سليم عنحوري', 1933, 1856, NULL, 'exact'),
  ('مهدي حجي', NULL, NULL, 1950, 'approx'),
  ('وردة اليازجي', 1924, 1838, NULL, 'exact'),
  ('ابن باجة الاندلسي', 1138, 1085, NULL, 'exact'),
  ('ابو الهدى الصيادي', 1909, 1850, NULL, 'exact'),
  ('صالح الشرنوبي', 1951, 1924, NULL, 'exact'),
  ('عمر الانسي', 1876, 1822, NULL, 'exact'),
  ('غادة السمان', NULL, 1942, 1980, 'exact'),
  ('فدوى طوقان', 2003, 1917, NULL, 'exact'),
  ('قاسم حداد', NULL, 1948, 1990, 'exact'),
  ('ابن لولو', 1350, NULL, NULL, 'approx'),
  ('اسماعيل صبري', 1923, 1854, NULL, 'exact'),
  ('المنازي', 1050, NULL, NULL, 'approx'),
  ('امين ناصر الدين', 1953, 1884, NULL, 'approx'),
  ('انس الحجار', NULL, NULL, 2010, 'approx'),
  ('حيدر بن سليمان الحلي', 1886, 1831, NULL, 'exact'),
  ('خشان خشان', NULL, NULL, 2000, 'approx'),
  ('سليمان الصولة', NULL, NULL, 1900, 'approx'),
  ('عبد الحميد السنوسي', NULL, NULL, 1950, 'approx'),
  ('معين بسيسو', 1984, 1926, NULL, 'exact'),
  ('ولي الدين يكن', 1921, 1873, NULL, 'exact'),
  ('أبو اليمن الكندي', 1217, 1132, NULL, 'exact'),
  ('بدر شاكر السياب', 1964, 1926, NULL, 'exact'),
  ('عبد الباقي العمري الفاروقي', 1861, 1790, NULL, 'exact'),
  ('عبد القادر الجزايري', 1883, 1808, NULL, 'exact'),
  ('علي بن محمد التهامي', 1025, NULL, NULL, 'exact'),
  ('لبيد بن ربيعة العامري', 661, NULL, NULL, 'approx'),
  ('ابراهيم بن هلال بن زهرون', 994, 925, NULL, 'exact'),
  ('ابن طفيل', 1185, 1105, NULL, 'exact'),
  ('الشاعر التونسي', NULL, NULL, 1900, 'approx'),
  ('عبدالرحيم بدر', NULL, NULL, 2000, 'approx'),
  ('ابن قضيب البان الحلبي', 1687, 1620, NULL, 'exact'),
  ('أبو الحسن السلامي', 1002, 948, NULL, 'exact'),
  ('أبو بكر الصديق', 634, 573, NULL, 'exact'),
  ('أبو بكر العنبري', NULL, NULL, 900, 'approx'),
  ('أبو جعفر الملاحي', NULL, NULL, 1200, 'approx'),
  ('أبو صخر الهذلي', 700, NULL, NULL, 'approx'),
  ('إبراهيم بن المهدي', 839, 779, NULL, 'exact'),
  ('ابراهيم بن العباس الصولي', 857, 792, NULL, 'exact'),
  ('ابن أبي الخصال', 1146, 1073, NULL, 'exact'),
  ('ابن الخياط', 1123, 1058, NULL, 'exact'),
  ('ابن الزيات', 847, 790, NULL, 'exact'),
  ('ابن العديم', 1262, 1192, NULL, 'exact'),
  ('ابن اللبانة الداني', 1113, NULL, NULL, 'exact'),
  ('ابن المُقري', 1433, 1354, NULL, 'exact'),
  ('ابن بقي القرطبي', 1145, NULL, NULL, 'exact'),
  ('ابن جبير', 1217, 1145, NULL, 'exact'),
  ('ابن زمرك', 1393, 1333, NULL, 'exact'),
  ('ابن سينا', 1037, 980, NULL, 'exact'),
  ('ابن هندو', 1019, NULL, NULL, 'approx'),
  ('ابو الحسن النوري', 907, NULL, NULL, 'exact'),
  ('ابو منصور الثعالبي', 1038, 961, NULL, 'exact'),
  ('اروى بنت عبد المطلب', 630, NULL, NULL, 'approx'),
  ('اشجع السلمي', 809, NULL, NULL, 'approx'),
  ('الاعمى التطيلي', 1126, NULL, NULL, 'exact'),
  ('البوصيري', 1295, 1213, NULL, 'exact'),
  ('الحاج غلوج', NULL, NULL, 1800, 'approx'),
  ('الخرنق بنت بدر', 600, NULL, NULL, 'approx'),
  ('الزبرقان بن بدر', 660, NULL, NULL, 'approx'),
  ('الشنفرى', 525, NULL, NULL, 'approx'),
  ('العباس بن مرداس', 639, NULL, NULL, 'approx'),
  ('العرجي', 738, NULL, NULL, 'approx'),
  ('الكميت بن زيد الاسدي', 744, 679, NULL, 'exact'),
  ('تميم الفاطمي', 984, 948, NULL, 'exact'),
  ('جبيهاء الأشجعي', NULL, NULL, 700, 'approx'),
  ('جليلة بنت مرة الشيبانية', NULL, NULL, 520, 'approx'),
  ('حازم القرطاجني', 1285, 1211, NULL, 'exact'),
  ('خالد بن الوليد', 642, 585, NULL, 'exact'),
  ('دريد بن الصمة', 630, NULL, NULL, 'approx'),
  ('رابعة العدوية', 801, 717, NULL, 'approx'),
  ('ربيعة الرقي', 814, NULL, NULL, 'approx'),
  ('زيادة بن زيد العذري', NULL, NULL, 700, 'approx'),
  ('سمنون المحب', 910, NULL, NULL, 'approx'),
  ('صالح بن عبد القدوس', 783, NULL, NULL, 'exact'),
  ('صردر', 1072, 1000, NULL, 'approx'),
  ('صريع الغواني', 815, NULL, NULL, 'approx'),
  ('صفوان التجيبي', NULL, NULL, 1200, 'approx'),
  ('عاتكة بنت زيد', 660, NULL, NULL, 'approx'),
  ('عبد الله بن الزبير الأسدي', 693, NULL, NULL, 'approx'),
  ('عبد المحسن الصوري', 1030, 951, NULL, 'exact'),
  ('عبيد الله بن عبدالله بن طاهر', 913, 837, NULL, 'exact'),
  ('عبيد بن الأبرص', 555, NULL, NULL, 'approx'),
  ('عز الدين ابن معقل المهلبي', 1288, 1207, NULL, 'approx'),
  ('علقمة الفحل', 590, NULL, NULL, 'approx'),
  ('عمرو بن الأهتم', 641, NULL, NULL, 'approx'),
  ('عمرو بن معدي كرب', 642, NULL, NULL, 'approx'),
  ('فاطمة الزهراء', 632, 605, NULL, 'approx'),
  ('فاطمة بنت الاحجم الخزاعية', NULL, NULL, 650, 'approx'),
  ('قس بن ساعدة', 600, NULL, NULL, 'approx'),
  ('قيس بن الخطيم', 600, NULL, NULL, 'approx'),
  ('كعب بن مالك الأنصاري', 673, NULL, NULL, 'approx'),
  ('ليلى الأخليلية', 704, NULL, NULL, 'approx'),
  ('ليلى الاخيلية', 704, NULL, NULL, 'approx'),
  ('محمد بن حمير الهمداني', NULL, NULL, 1100, 'approx'),
  ('نزهون بنت القلاعي الغرناطية', 1155, NULL, NULL, 'approx'),
  ('نهشل بن حري', NULL, NULL, 660, 'approx'),
  ('هند بنت عتبة', 636, NULL, NULL, 'approx'),
  ('يوسف الثالث', 1417, 1376, NULL, 'exact'),
  ('الباجي المسعودي', 1880, 1810, NULL, 'approx'),
  ('علي قوادري', NULL, NULL, 2010, 'approx'),
  ('محيي الدين ابن الشهرزوري', 1193, 1116, NULL, 'approx'),
  ('ابن الطيب الشرقي', 1757, 1698, NULL, 'exact'),
  ('ابن جزي الكلبي', 1340, 1294, NULL, 'exact'),
  ('ابن ماكولا', 1082, 1030, NULL, 'exact'),
  ('المحبي', 1699, 1651, NULL, 'exact'),
  ('الهبل', 1668, 1613, NULL, 'exact'),
  ('الورغي', 1776, NULL, NULL, 'approx'),
  ('الياس ابو شبكة', 1947, 1903, NULL, 'exact'),
  ('امين الجندي الحمصي', 1841, 1766, NULL, 'exact'),
  ('بهاء الدين العاملي', 1621, 1547, NULL, 'exact'),
  ('ختام حمودة', NULL, NULL, 2010, 'approx'),
  ('رايطة بنت شيظم النميرية', NULL, NULL, 650, 'approx'),
  ('عباد بن شداد اليربوعي', NULL, NULL, 700, 'approx'),
  ('محمد الاسمر', 1956, 1900, NULL, 'exact'),
  ('محمد الخلخالي', NULL, NULL, 1900, 'approx'),
  ('ياسر الاطرش', NULL, NULL, 2010, 'approx'),
  ('يوسف بن أبي الفتح', NULL, NULL, 1650, 'approx'),
  ('احلام بناوي', NULL, NULL, 2010, 'approx'),
  ('الحسن بن عمرو الاباضي', NULL, NULL, 1100, 'approx'),
  ('الشماخ بن ضرار الذبياني', 656, NULL, NULL, 'approx'),
  ('امية بن عبد العزيز الداني', 1134, NULL, NULL, 'exact'),
  ('حسن قفطان', 1861, 1795, NULL, 'approx'),
  ('طانيوس عبده', 1926, 1869, NULL, 'exact'),
  ('ظهير الدين الروذراوري', 1113, 1045, NULL, 'exact'),
  ('عامر بن الظرب العدواني', 570, NULL, NULL, 'approx'),
  ('علاء سالم', NULL, NULL, 2010, 'approx'),
  ('عمر الرافعي', NULL, NULL, 1900, 'approx'),
  ('مطيع بن اياس', 787, NULL, NULL, 'approx'),
  ('موفق الدين بن ابي الحديد', 1231, NULL, NULL, 'approx'),
  ('نبوية موسى', 1951, 1886, NULL, 'exact'),
  ('ابن سارة الاندلسي', 1123, NULL, NULL, 'exact'),
  ('ابو الحسن السنجاني', NULL, NULL, 1100, 'approx'),
  ('ابو غالب الواسطي', NULL, NULL, 1050, 'approx'),
  ('ابو نصر القشيري', 1120, 1058, NULL, 'approx'),
  ('احمد القوصي', NULL, NULL, 1300, 'approx'),
  ('احمد فارس الشدياق', 1887, 1805, NULL, 'exact'),
  ('العيزار بن الاخنس الطايي', NULL, NULL, 650, 'approx'),
  ('القاسم صدر الافاضل', 1218, NULL, NULL, 'approx'),
  ('المفتي عبد اللطيف فتح الله', 1844, 1775, NULL, 'approx'),
  ('المفدي زكريا', 1977, 1908, NULL, 'exact'),
  ('المنفتل', NULL, NULL, 1100, 'approx'),
  ('النصيبي القوصي', NULL, NULL, 1300, 'approx'),
  ('باقر العطار', 1813, 1751, NULL, 'approx'),
  ('حيدر التميمي', NULL, NULL, 1900, 'approx'),
  ('خليل مردم بك', 1959, 1895, NULL, 'exact'),
  ('ذبية بنت بيشة الفهمية', NULL, NULL, 650, 'approx'),
  ('سيف الدين المشد', 1257, 1200, NULL, 'approx'),
  ('شاعر الحمراء', NULL, NULL, 1400, 'approx'),
  ('طاهر زمخشري', 1987, 1914, NULL, 'exact'),
  ('طه حسين', 1973, 1889, NULL, 'exact'),
  ('عايشة التيمورية', 1902, 1840, NULL, 'exact'),
  ('عبد الله بلفقيه', NULL, NULL, 1950, 'approx'),
  ('عبد المجيد قاسم الطرشاني', NULL, NULL, 2000, 'approx'),
  ('عبد المنعم الجلياني', 1207, 1122, NULL, 'exact'),
  ('عبد الوهاب البياتي', 1999, 1926, NULL, 'exact'),
  ('عمر ابو ريشة', 1990, 1910, NULL, 'exact'),
  ('عيينة بن عبد الرحمن ابو المنهال', NULL, NULL, 750, 'approx'),
  ('قسطاكي الحمصي', 1941, 1858, NULL, 'exact'),
  ('مثنى ابراهيم دهام', NULL, NULL, 2010, 'approx'),
  ('محمد بن علي بن ابي مروان', NULL, NULL, 1100, 'approx'),
  ('مكي بن هبيرة', NULL, NULL, 1100, 'approx'),
  ('نسيب النكدي', NULL, NULL, 1900, 'approx'),
  ('يحيى ابن البحتري', 900, NULL, NULL, 'approx'),
  ('يحيى قصادي', NULL, NULL, 2000, 'approx'),
  ('أبو الحسن بن خروف', 1212, 1150, NULL, 'approx'),
  ('ابتسام البرغوثي', NULL, NULL, 2000, 'approx'),
  ('ابراهيم الاحدب', 1891, 1826, NULL, 'exact'),
  ('ابن ابي الاصبع', 1256, 1197, NULL, 'exact'),
  ('ابن الافرنجية', NULL, NULL, 1200, 'approx'),
  ('ابن الصيقل الجزري', 1225, NULL, NULL, 'approx'),
  ('ابن رشيد البغدادي', NULL, NULL, 1200, 'approx'),
  ('ابن زيلاق', NULL, NULL, 1000, 'approx'),
  ('ابن صاحب الصلاة ( ابن المناصف )', 1223, 1170, NULL, 'approx'),
  ('ابن فضال الحلواني', NULL, NULL, 1100, 'approx'),
  ('ابن قرناص', 1331, 1258, NULL, 'approx'),
  ('ابن مالك', 1274, 1203, NULL, 'exact'),
  ('ابو الجوايز الواسطي', 1099, NULL, NULL, 'approx'),
  ('ابو العباس المرسي', 1287, 1219, NULL, 'exact'),
  ('ابو الهيثم المعري اخو ابي العلاء', 1050, NULL, NULL, 'approx'),
  ('ابو سعيد الحجري', NULL, NULL, 1100, 'approx'),
  ('ابو علي ابن فورجه', 1060, NULL, NULL, 'approx'),
  ('احمد الكاشف', 1948, 1878, NULL, 'exact'),
  ('الاخطل الصغير بشارة الخوري', 1968, 1885, NULL, 'exact'),
  ('الحسين بن علي بن ابي طالب', 680, 626, NULL, 'exact'),
  ('المطران جرمانوس', 1897, 1810, NULL, 'approx'),
  ('الوتار', NULL, NULL, 1900, 'approx'),
  ('الوزير ابو حفص بن برد الاصغر', 1053, NULL, NULL, 'approx'),
  ('انس ابراهيم الدغيم', NULL, NULL, 2010, 'approx'),
  ('ايمان المحمداوي', NULL, NULL, 2010, 'approx'),
  ('تركي المعيني', NULL, NULL, 2000, 'approx'),
  ('ثابت بن سنان الصابي', 976, NULL, NULL, 'exact'),
  ('ثابت قطنة', 728, NULL, NULL, 'approx'),
  ('جعفر الحلي', 1897, 1861, NULL, 'exact'),
  ('حبيش بن عبد الله الهمداني', NULL, NULL, 900, 'approx'),
  ('داود بن عيسى الايوبي', 1227, 1178, NULL, 'approx'),
  ('ذو اللسانين النطنزي', 1108, NULL, NULL, 'approx'),
  ('رمضان عبد الحميد زيدان', NULL, NULL, 2000, 'approx'),
  ('زينب فواز', 1914, 1860, NULL, 'exact'),
  ('عبد الرحيم احمد الصغير(الماسخ)', NULL, NULL, 1900, 'approx'),
  ('عبد العزيز الجاسر', NULL, NULL, 1980, 'approx'),
  ('عبد الله بن علي الخليلي', 1968, 1880, NULL, 'approx'),
  ('عبدالحسين الجواهري', 1915, 1850, NULL, 'approx'),
  ('علاء الدين الوداعي', 1310, 1252, NULL, 'approx'),
  ('عمر تقي الدين الرافعي', NULL, NULL, 1900, 'approx'),
  ('فاروق جويدة', NULL, 1946, 1990, 'exact'),
  ('فتيان الشاغوري', 1220, 1143, NULL, 'exact'),
  ('محسن الجواهري', NULL, NULL, 1900, 'approx'),
  ('محمد المقرن', NULL, NULL, 2000, 'approx'),
  ('محمد توفيق علي', NULL, NULL, 1950, 'approx'),
  ('محمد تيمور', 1921, 1892, NULL, 'exact'),
  ('محمد كمال', NULL, NULL, 1950, 'approx'),
  ('مرة بن محكان السعدي', NULL, NULL, 650, 'approx'),
  ('مهدي الطالقاني', NULL, NULL, 1850, 'approx'),
  ('مهند مشعل عبد العزيز', NULL, NULL, 2010, 'approx'),
  ('موسى شرارة', 1904, 1852, NULL, 'approx'),
  ('نوري سراج الوايلي', NULL, NULL, 2000, 'approx'),
  ('هند جارية الشاطبي', NULL, NULL, 1200, 'approx'),
  ('أبو المحاسن الشواء', 1240, 1179, NULL, 'exact'),
  ('ابراهيم بن سيار النظام', 845, 775, NULL, 'approx'),
  ('ابن السكون الكاتب الحلي', 1210, NULL, NULL, 'approx'),
  ('ابن الظهير الاربلي', 1276, 1213, NULL, 'exact'),
  ('ابنة حذاق الحنفي', NULL, NULL, 650, 'approx'),
  ('ابو عبدة الوزير', NULL, NULL, 1000, 'approx'),
  ('ابو محمد عبد الله العسال', NULL, NULL, 1000, 'approx'),
  ('احمد تقي الدين', NULL, NULL, 1950, 'approx'),
  ('اسعد طراد', NULL, NULL, 1950, 'approx'),
  ('الاسود بن يعفر النهشلي', 600, NULL, NULL, 'approx'),
  ('الامام الشوكاني', 1834, 1760, NULL, 'exact'),
  ('البديع الدمشقي', NULL, NULL, 1600, 'approx'),
  ('الحداد القيسي', NULL, NULL, 1200, 'approx'),
  ('الفروخي ابو نصر الاواني', NULL, NULL, 1100, 'approx'),
  ('جاسم الصحيح', NULL, 1964, 2000, 'exact'),
  ('خليل ناصيف اليازجي', 1889, 1856, NULL, 'exact'),
  ('رشيد ايوب', 1941, 1871, NULL, 'exact'),
  ('زفر بن الحارث الكلابي', 692, NULL, NULL, 'approx'),
  ('زكي الصبيحاوي', NULL, NULL, 1950, 'approx'),
  ('زكي مبارك', 1952, 1892, NULL, 'exact'),
  ('شيرين شيحه', NULL, NULL, 2010, 'approx'),
  ('ضمد كاظم الوسمي', NULL, NULL, 2000, 'approx'),
  ('عامر بن مالك الفزاري', NULL, NULL, 600, 'approx'),
  ('عايشة الباعونية', 1517, 1456, NULL, 'exact'),
  ('عبد الحكيم بن عامر الحجري', NULL, NULL, 1900, 'approx'),
  ('عبد العزيز بن زرارة الكلابي', NULL, NULL, 660, 'approx'),
  ('عبد اللطيف الصيرفى', NULL, NULL, 1700, 'approx'),
  ('عبدالله النديم', 1896, 1843, NULL, 'exact'),
  ('عدي بن حاتم الطايي', 687, 587, NULL, 'approx'),
  ('عمارة بن صالح عبد المالك', NULL, NULL, 800, 'approx'),
  ('عمر اليافي', 1818, 1747, NULL, 'approx'),
  ('فروة بن نوفل الاشجعي', 661, NULL, NULL, 'approx'),
  ('كفا خضر', NULL, NULL, 2010, 'approx'),
  ('كنعان الموسوي', NULL, NULL, 2000, 'approx'),
  ('لسان الدين الخطيب', 1374, 1313, NULL, 'exact'),
  ('محمد احمد المجالي', NULL, NULL, 2000, 'approx'),
  ('محمد الفايز القيرواني', NULL, NULL, 1100, 'approx'),
  ('محمد الماغوط', 2006, 1934, NULL, 'exact'),
  ('محمد خضير', NULL, NULL, 2000, 'approx'),
  ('محمود مفلح', NULL, 1943, 1990, 'exact'),
  ('مرسي شاكر طنطاوي', NULL, NULL, 1950, 'approx'),
  ('مريم يمق ( زاهية بنت البحر )', 1965, 1900, NULL, 'approx'),
  ('منصور بن اسماعيل الفقيه', 918, NULL, NULL, 'exact'),
  ('موسى الطالقاني', NULL, NULL, 1850, 'approx'),
  ('ميخاييل خير الله ويردي', NULL, NULL, 1950, 'approx'),
  ('نافع محمد النافع', NULL, NULL, 2000, 'approx'),
  ('ناهدة الحلبي', NULL, NULL, 2000, 'approx'),
  ('إبراهيم عبد القادر المازني', 1949, 1889, NULL, 'exact'),
  ('ابراهيم طلحة', NULL, NULL, 1900, 'approx'),
  ('ابن الدهان', 1258, 1194, NULL, 'approx'),
  ('ابن سيد الناس', 1334, 1273, NULL, 'exact'),
  ('ابو الحسن ابن النرسي', NULL, NULL, 1100, 'approx'),
  ('ابو القاسم الزاهي', 962, 928, NULL, 'approx'),
  ('ابو اليسر المعري', NULL, NULL, 1050, 'approx'),
  ('ابو عبد الله البغوي', 929, NULL, NULL, 'approx'),
  ('ابو علي المنطقي', NULL, NULL, 1000, 'approx'),
  ('احمد الصابوني', NULL, NULL, 1900, 'approx'),
  ('احمد محرم', 1945, 1877, NULL, 'exact'),
  ('اسلام عكرية', NULL, NULL, 2010, 'approx'),
  ('اسماعيل سري الدهشان', NULL, NULL, 1900, 'approx'),
  ('ام خالد النميرية', NULL, NULL, 650, 'approx'),
  ('تميم البرغوثي', NULL, 1977, 2010, 'exact'),
  ('راشد حسين', 1977, 1936, NULL, 'exact'),
  ('رياض منصور', NULL, NULL, 2000, 'approx'),
  ('زين العابدين الضبيبي', NULL, NULL, 1900, 'approx'),
  ('ستيرة العصيبية', NULL, NULL, 650, 'approx'),
  ('سعيد عقل', 2014, 1911, NULL, 'exact'),
  ('سميح القاسم', 2014, 1939, NULL, 'exact'),
  ('عبد القادر بدران', 1927, 1846, NULL, 'exact'),
  ('عبد الناصر عليوي العبيدي', NULL, NULL, 2010, 'approx'),
  ('عبدالحسين الحلي', 1955, 1875, NULL, 'approx'),
  ('عبدالله الخضري', NULL, NULL, 2000, 'approx'),
  ('عبدة بن الطبيب', 630, NULL, NULL, 'approx'),
  ('عبده فايز الزبيدي', NULL, NULL, 2010, 'approx'),
  ('علاء خلف', NULL, NULL, 2010, 'approx'),
  ('عماد الدين الاصبهاني', 1201, 1125, NULL, 'exact'),
  ('قتيلة بنت النضر', 624, NULL, NULL, 'approx'),
  ('كريم النعمان', NULL, NULL, 2000, 'approx'),
  ('محمد حسين ال ياسين', NULL, NULL, 1950, 'approx'),
  ('محمد حمدي غانم', NULL, NULL, 2000, 'approx'),
  ('مرسي شاكر الطنطاوي', NULL, NULL, 1950, 'approx'),
  ('مير علي ابو طبيخ', NULL, NULL, 1900, 'approx'),
  ('ناجية بن محمد الكاتب', NULL, NULL, 1000, 'approx'),
  ('ناصيف اليازجي', 1871, 1800, NULL, 'exact'),
  ('آمنة بنت عتيبة', NULL, NULL, 650, 'approx'),
  ('أبو الحسن بن حريق', 1223, 1150, NULL, 'approx'),
  ('أبو الحسين الجزار', 1281, 1204, NULL, 'exact'),
  ('أبو الحسين النوري', 907, NULL, NULL, 'exact'),
  ('أبو الشيص الخزاعي', 811, NULL, NULL, 'approx'),
  ('أبو الطمحان القيني', 650, NULL, NULL, 'approx'),
  ('أبو العيناء', 896, 808, NULL, 'exact'),
  ('أبو الوليد الحميري', NULL, NULL, 1000, 'approx'),
  ('أبو بكر الخالدي', 990, NULL, NULL, 'approx'),
  ('أبو بكر بن القوطية', 977, NULL, NULL, 'exact'),
  ('أبو زبيد الطائي', 681, NULL, NULL, 'approx'),
  ('أبو محجن الثقفي', 637, NULL, NULL, 'approx'),
  ('أبو هفان المهزمي', 871, NULL, NULL, 'approx'),
  ('أبو وجزة السعدي', 747, NULL, NULL, 'approx'),
  ('أحمد بن أبي فنن', 874, NULL, NULL, 'approx'),
  ('أمية بن أبي الصلت', 626, NULL, NULL, 'approx'),
  ('أوس بن حجر', 600, NULL, NULL, 'approx'),
  ('إبراهيم الصولي', NULL, NULL, 900, 'approx'),
  ('ابراهيم الحصري', 1061, NULL, NULL, 'approx'),
  ('ابن أبي البشر', NULL, NULL, 1100, 'approx'),
  ('ابن اسد الفارقي', NULL, NULL, 1150, 'approx'),
  ('ابن الابار الاشبيلي', 1260, 1199, NULL, 'exact'),
  ('ابن الابار القضاعي البنلسي', 1260, 1199, NULL, 'exact'),
  ('ابن التلميذ', 1165, 1073, NULL, 'exact'),
  ('ابن الحاج البلفيقي', 1372, 1290, NULL, 'approx'),
  ('ابن الحناط', 1046, NULL, NULL, 'approx'),
  ('ابن الرعلاء', NULL, NULL, 600, 'approx'),
  ('ابن الزقاق', 1134, 1096, NULL, 'approx'),
  ('ابن الصباغ الجذامي', NULL, NULL, 1200, 'approx'),
  ('ابن بابك', 1019, NULL, NULL, 'approx'),
  ('ابن باجه', 1138, 1085, NULL, 'exact'),
  ('ابن حجاج', 1001, 941, NULL, 'exact'),
  ('ابن حديدة', NULL, NULL, 1100, 'approx'),
  ('ابن خلكان', 1282, 1211, NULL, 'exact'),
  ('ابن سعد الخير البلنسي', NULL, NULL, 1150, 'approx'),
  ('ابن قسيم الحموي', NULL, NULL, 1300, 'approx'),
  ('ابن مكنسة الاسكندراني', 1105, NULL, NULL, 'approx'),
  ('ابن هذيل', NULL, NULL, 1200, 'approx'),
  ('ابن همام', NULL, NULL, 1000, 'approx'),
  ('ابن وهيب الحميري', 839, NULL, NULL, 'approx'),
  ('ابنة عقيل بن ابي طالب', NULL, NULL, 660, 'approx'),
  ('ابو الحسن الجوهري', NULL, NULL, 1000, 'approx'),
  ('ابو الحسن النعيمي', 1000, NULL, NULL, 'approx'),
  ('ابو الشغب العبسي', NULL, NULL, 700, 'approx'),
  ('ابو الشيص محمد', 811, NULL, NULL, 'approx'),
  ('ابو الفضل الميكالي', 1044, NULL, NULL, 'exact'),
  ('ابو عدي المعري', NULL, NULL, 1050, 'approx'),
  ('ابو علي الخواري البيهقي', NULL, NULL, 1100, 'approx'),
  ('ابوالثناء شهاب الدين محمود الالوسي', 1854, 1802, NULL, 'exact'),
  ('احمد زكي ابو شادي', 1955, 1892, NULL, 'exact'),
  ('احمد فتحي', NULL, NULL, 1950, 'approx'),
  ('اسماء بنت ابي بكر', 692, 595, NULL, 'approx'),
  ('الأخطل', 710, 640, NULL, 'approx'),
  ('الأرجاني', 1149, 1068, NULL, 'exact'),
  ('الأسود التغلبي', NULL, NULL, 600, 'approx'),
  ('الأعشى', 629, 570, NULL, 'approx'),
  ('الأقرع بن معاذ', NULL, NULL, 620, 'approx'),
  ('الاصبغ القرشي', NULL, NULL, 700, 'approx'),
  ('الجيداء بنت زاهر الزبيدية', NULL, NULL, 600, 'approx'),
  ('الحارث الجرمي', NULL, NULL, 650, 'approx'),
  ('الحسين بن اسد العامري', NULL, NULL, 1000, 'approx'),
  ('الحسين بن الضحاك', 864, 778, NULL, 'exact'),
  ('الحسين بن علي', 680, 626, NULL, 'exact'),
  ('الحصين بن حمام الفزاري', NULL, NULL, 600, 'approx'),
  ('الخريمي', 821, NULL, NULL, 'approx'),
  ('الخنساء بنت التيجان', NULL, NULL, 600, 'approx'),
  ('الخيبري الخارجي', NULL, NULL, 700, 'approx'),
  ('الراضي ابن المعتمد بن عباد', 1091, NULL, NULL, 'approx'),
  ('الراضي بالله', 940, 909, NULL, 'exact'),
  ('السراج الوراق', 1296, 1218, NULL, 'exact'),
  ('السموأل', 560, NULL, NULL, 'approx'),
  ('الشريف العقيلي', NULL, NULL, 1100, 'approx'),
  ('الشريف الغرناطي', 1359, 1312, NULL, 'approx'),
  ('الشيخ الرييس ابو نصر القايني', NULL, NULL, 1050, 'approx'),
  ('الصمة القشيري', 707, NULL, NULL, 'approx'),
  ('الطرماح', 743, NULL, NULL, 'approx'),
  ('الطفيل الغنوي', 600, NULL, NULL, 'approx'),
  ('العجاج', 715, NULL, NULL, 'approx'),
  ('العيوق بنت مسعود', NULL, NULL, 650, 'approx'),
  ('القتال الكلابي', 705, NULL, NULL, 'approx'),
  ('الكميت بن زيد', 744, 679, NULL, 'exact'),
  ('المأمون', 833, 786, NULL, 'exact'),
  ('المتوكل الليثي', 695, NULL, NULL, 'approx'),
  ('المثقب العبدي', 587, NULL, NULL, 'approx'),
  ('المعتضد بن عباد', 1069, 1015, NULL, 'exact'),
  ('المقنع الكندي', NULL, NULL, 680, 'approx'),
  ('الملك المعز محيي الدين الايوبي', 1249, NULL, NULL, 'approx'),
  ('المهذب بن الزبير', 1170, 1112, NULL, 'approx'),
  ('الميكالي', 1044, NULL, NULL, 'exact'),
  ('الناشئ الأكبر', 906, NULL, NULL, 'exact'),
  ('النَهشَلي', NULL, NULL, 1000, 'approx'),
  ('الوزير المهلبي', 963, 903, NULL, 'exact'),
  ('ام ابي الحسن السلامي', NULL, NULL, 1000, 'approx'),
  ('ام صريع الكندية', NULL, NULL, 650, 'approx'),
  ('تماضر بنت الشريد', 645, 575, NULL, 'approx'),
  ('توبة بن الحمير الخفاجي', 704, NULL, NULL, 'approx'),
  ('جورج جريس فرح', NULL, NULL, 1980, 'approx'),
  ('حاجب الفيل', NULL, NULL, 900, 'approx'),
  ('ذو المفاخر الهمذاني النيرماني', NULL, NULL, 1100, 'approx'),
  ('ريطة بنت عاصم الهوازنية', NULL, NULL, 620, 'approx'),
  ('سديد الدولة ابن الانباري', 1200, 1130, NULL, 'approx'),
  ('سليمى بنت المهلهل', NULL, NULL, 530, 'approx'),
  ('سهل الغرناطي', NULL, NULL, 1300, 'approx'),
  ('سيف الرحبي', NULL, 1956, 2000, 'exact'),
  ('شرف الدين البوصيري', 1295, 1213, NULL, 'exact'),
  ('شهاب الدين الالوسي', 1854, 1802, NULL, 'exact'),
  ('شهاب الدين الخلوف', 1479, 1425, NULL, 'approx'),
  ('ضرار الفهري', NULL, NULL, 700, 'approx'),
  ('طريح بن إسماعيل الثقفي', 782, NULL, NULL, 'approx'),
  ('ظافر الحداد', 1134, NULL, NULL, 'exact'),
  ('عامرية الكثيب', NULL, NULL, 1200, 'approx'),
  ('عايشة بنت احمد القرطبية', 1010, NULL, NULL, 'exact'),
  ('عبد العزيز المقالح', 2022, 1937, NULL, 'exact'),
  ('عبد الغفار الأخرس', 1873, 1804, NULL, 'exact'),
  ('عبد المحسن الصوري بن غلبون', 1030, 951, NULL, 'exact'),
  ('عبد الملك الحارثي', NULL, NULL, 1000, 'approx'),
  ('عبد المهيمن الحضرمي', 1414, 1327, NULL, 'approx'),
  ('عبدالله جدي', NULL, NULL, 2000, 'approx'),
  ('عبيد الله الجَعفي', NULL, NULL, 700, 'approx'),
  ('عبيد الله بن مسعود الهذلي', NULL, NULL, 700, 'approx'),
  ('عبيدة اليشكري', NULL, NULL, 600, 'approx'),
  ('عرقلة الكلبي الدمشقي', 1171, 1106, NULL, 'exact'),
  ('عروة بن ادية', 697, NULL, NULL, 'approx'),
  ('عروة بن حزام', 650, NULL, NULL, 'approx'),
  ('علي بن الحسين', 713, 659, NULL, 'approx'),
  ('علي بن فضال المجاشعي', 1086, NULL, NULL, 'approx'),
  ('عمرة بنت رواحة الانصارية', NULL, NULL, 630, 'approx'),
  ('عمرو الباهلي', NULL, NULL, 700, 'approx'),
  ('عمرو بن قميئة', 540, NULL, NULL, 'approx'),
  ('فخر الدين ابن هبيرة', 1165, 1105, NULL, 'approx'),
  ('قطري بن الفجاءة', 699, NULL, NULL, 'exact'),
  ('قيس بن عاصم المنقري', 640, NULL, NULL, 'approx'),
  ('كاظم الخضري', NULL, NULL, 1900, 'approx'),
  ('لقيط بن زرارة الدارمي', NULL, NULL, 590, 'approx'),
  ('ليلى العفيفة', NULL, NULL, 600, 'approx'),
  ('ليلى بنت سلمى', NULL, NULL, 600, 'approx'),
  ('مالك الأشتر', 658, NULL, NULL, 'approx'),
  ('ماني الموسوس', 862, NULL, NULL, 'approx'),
  ('متمم اليربوعي', 650, NULL, NULL, 'approx'),
  ('محسن الامين', 1952, 1867, NULL, 'exact'),
  ('محمد بن بشير الخارجي', NULL, NULL, 750, 'approx'),
  ('محمد بن وهيب الحميري', 839, NULL, NULL, 'approx'),
  ('محمود حسن اسماعيل', 1977, 1910, NULL, 'exact'),
  ('مرج الكحل', 1236, NULL, NULL, 'exact'),
  ('مروان الطليق', NULL, NULL, 1050, 'approx'),
  ('مروان بن أبي حفصة', 797, 723, NULL, 'exact'),
  ('مسكين الدارمي', 708, NULL, NULL, 'approx'),
  ('معاوية بن أبي سفيان', 680, 602, NULL, 'exact'),
  ('مهدي البغدادي', NULL, NULL, 1900, 'approx'),
  ('نازك الملايكة', 2007, 1923, NULL, 'exact'),
  ('نافع بن الأسود', NULL, NULL, 650, 'approx'),
  ('هارون الرشيد', 809, 763, NULL, 'exact'),
  ('هدبة بن الخشرم', 670, NULL, NULL, 'approx'),
  ('هزيلة الجديسية', NULL, NULL, 520, 'approx'),
  ('هند الضبابية', NULL, NULL, 650, 'approx'),
  ('هند بنت النعمان', NULL, NULL, 620, 'approx'),
  ('ورقاء بن زهير', NULL, NULL, 580, 'approx'),
  ('وضاح اليمن', 708, NULL, NULL, 'approx'),
  ('يحيى بن زياد الحارثي', NULL, NULL, 780, 'approx'),
  ('يزيد المهلبي', NULL, NULL, 850, 'approx')
)
UPDATE public.poets po
SET death_year      = b.death_year,
    birth_year      = b.birth_year,
    active_year     = b.active_year,
    date_confidence = b.date_confidence
FROM b
WHERE po.name = b.name;

-- Derived, never hand-entered. poet_century() is the single definition, added
-- in 20260815000000; poems.century stays a CACHE of it so every existing
-- server.js query path (century, centuryFrom/centuryTo, undated, includeUndated)
-- keeps working with no code change.
UPDATE public.poems p
SET century = public.poet_century(po.death_year, po.active_year, po.birth_year)
FROM public.poets po
WHERE p.poet_id = po.id
  AND p.century IS DISTINCT FROM public.poet_century(po.death_year, po.active_year, po.birth_year);

COMMIT;
