-- Migration to add detailed accessibility factor scores and 0-10 derived score
-- Generated by migration tool on $(date)

-- Add new table to store per-factor scores for each poem
CREATE TABLE IF NOT EXISTS poem_factor_scores (
    poem_id INTEGER REFERENCES poems(id) ON DELETE CASCADE,
    factor_name TEXT NOT NULL,  -- e.g., 'mood', 'topic', 'motif', 'contemplation', 'syntax', etc.
    score SMALLINT,  -- score from 0 to 10
    UNIQUE (poem_id, factor_name)
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_poem_factor_scores_poem_id ON poem_factor_scores (poem_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_poem_factor_scores_unique ON poem_factor_scores (poem_id, factor_name);

-- Add JSONB column to store aggregated factors maybe (optional)
-- ALTER TABLE poems ADD COLUMN IF NOT EXISTS factor_scores JSONB;

-- Optional: Add columns to store precomputed 0-10 derived score per poem
-- If you want to store derived 0-10 score directly:
ALTER TABLE public.poems ADD COLUMN IF NOT EXISTS access_score SMALLINT;

-- Optional: Add trigger to auto-calculate derived scores (if needed)
-- This migration just adds the structural support; actual scoring logic is in application code.

-- Seed sample data maybe? Not required.

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_poem_factor_scores_poem ON poem_factor_scores (poem_id);