-- Add English name column to poets table for bilingual display
ALTER TABLE public.poets ADD COLUMN IF NOT EXISTS name_en TEXT;

-- Populate English names for known poets
-- This covers the major classical and modern Arabic poets in the database
UPDATE public.poets SET name_en = CASE name
  WHEN 'المتنبي' THEN 'Al-Mutanabbi'
  WHEN 'محمود درويش' THEN 'Mahmoud Darwish'
  WHEN 'نزار قباني' THEN 'Nizar Qabbani'
  WHEN 'أبو العلاء المعري' THEN 'Al-Ma''arri'
  WHEN 'عنترة بن شداد' THEN 'Antarah ibn Shaddad'
  WHEN 'أبو الطيب المتنبي' THEN 'Al-Mutanabbi'
  WHEN 'امرؤ القيس' THEN 'Imru'' al-Qais'
  WHEN 'أبو نواس' THEN 'Abu Nuwas'
  WHEN 'أبو تمام' THEN 'Abu Tammam'
  WHEN 'البحتري' THEN 'Al-Buhturi'
  WHEN 'أبو فراس الحمداني' THEN 'Abu Firas al-Hamdani'
  WHEN 'الشريف الرضي' THEN 'Al-Sharif al-Radi'
  WHEN 'ابن زيدون' THEN 'Ibn Zaydun'
  WHEN 'المعتمد بن عباد' THEN 'Al-Mu''tamid ibn Abbad'
  WHEN 'أبو العتاهية' THEN 'Abu al-Atahiya'
  WHEN 'الأخطل' THEN 'Al-Akhtal'
  WHEN 'جرير' THEN 'Jarir'
  WHEN 'الفرزدق' THEN 'Al-Farazdaq'
  WHEN 'أبو البقاء الرندي' THEN 'Abu al-Baqa al-Rundi'
  WHEN 'أبو الأسود الدؤلي' THEN 'Abu al-Aswad al-Du''ali'
  WHEN 'أبو إسحاق الإلبيري' THEN 'Abu Ishaq al-Ilbiri'
  WHEN 'أبو الطمحان القيني' THEN 'Abu al-Tamhan al-Qayni'
  WHEN 'بدر شاكر السياب' THEN 'Badr Shakir al-Sayyab'
  WHEN 'أحمد شوقي' THEN 'Ahmad Shawqi'
  WHEN 'حافظ إبراهيم' THEN 'Hafiz Ibrahim'
  WHEN 'إيليا أبو ماضي' THEN 'Elia Abu Madi'
  WHEN 'جبران خليل جبران' THEN 'Khalil Gibran'
  WHEN 'أدونيس' THEN 'Adonis'
  WHEN 'سميح القاسم' THEN 'Samih al-Qasim'
  WHEN 'فدوى طوقان' THEN 'Fadwa Tuqan'
  WHEN 'غادة السمان' THEN 'Ghada al-Samman'
  WHEN 'أمل دنقل' THEN 'Amal Dunqul'
  WHEN 'صلاح عبد الصبور' THEN 'Salah Abd al-Sabur'
  WHEN 'عبد الرحمن الأبنودي' THEN 'Abdel Rahman el-Abnudi'
  WHEN 'أحمد مطر' THEN 'Ahmad Matar'
  WHEN 'محمد الماغوط' THEN 'Muhammad al-Maghut'
  WHEN 'الخنساء' THEN 'Al-Khansa'
  WHEN 'ابن الرومي' THEN 'Ibn al-Rumi'
  WHEN 'ابن الفارض' THEN 'Ibn al-Farid'
  WHEN 'المهلهل بن ربيعة' THEN 'Al-Muhalhil'
  WHEN 'طرفة بن العبد' THEN 'Tarafa ibn al-Abd'
  WHEN 'زهير بن أبي سلمى' THEN 'Zuhayr ibn Abi Sulma'
  WHEN 'لبيد بن ربيعة' THEN 'Labid ibn Rabi''a'
  WHEN 'عمرو بن كلثوم' THEN 'Amr ibn Kulthum'
  WHEN 'الحارث بن حلزة' THEN 'Al-Harith ibn Hilliza'
  WHEN 'النابغة الذبياني' THEN 'Al-Nabigha al-Dhubyani'
  WHEN 'حسان بن ثابت' THEN 'Hassan ibn Thabit'
  WHEN 'كعب بن زهير' THEN 'Ka''b ibn Zuhayr'
  WHEN 'الأعشى' THEN 'Al-A''sha'
  WHEN 'ذو الرمة' THEN 'Dhu al-Rumma'
  WHEN 'بشار بن برد' THEN 'Bashshar ibn Burd'
  WHEN 'ابن المقفع' THEN 'Ibn al-Muqaffa'
  WHEN 'الجاحظ' THEN 'Al-Jahiz'
  WHEN 'المنفلوطي' THEN 'Al-Manfaluti'
  WHEN 'معروف الرصافي' THEN 'Ma''ruf al-Rusafi'
  WHEN 'إبراهيم ناجي' THEN 'Ibrahim Naji'
  WHEN 'عمر أبو ريشة' THEN 'Omar Abu Risha'
  WHEN 'ميخائيل نعيمة' THEN 'Mikha''il Na''ima'
  WHEN 'أبو القاسم الشابي' THEN 'Abu al-Qasim al-Shabbi'
  WHEN 'بلند الحيدري' THEN 'Buland al-Haidari'
  WHEN 'عبد الوهاب البياتي' THEN 'Abd al-Wahhab al-Bayati'
  WHEN 'نازك الملائكة' THEN 'Nazik al-Mala''ika'
  WHEN 'توفيق زياد' THEN 'Tawfiq Zayyad'
  WHEN 'مظفر النواب' THEN 'Muzaffar al-Nawab'
  -- Additional classical poets
  WHEN 'الشنفرى' THEN 'Al-Shanfara'
  WHEN 'تأبط شرا' THEN 'Ta''abbata Sharran'
  WHEN 'الأصمعي' THEN 'Al-Asma''i'
  WHEN 'ابن خلدون' THEN 'Ibn Khaldun'
  WHEN 'ابن حزم' THEN 'Ibn Hazm'
  WHEN 'ابن سينا' THEN 'Ibn Sina'
  WHEN 'الحلاج' THEN 'Al-Hallaj'
  WHEN 'ابن الخطيب' THEN 'Ibn al-Khatib'
  WHEN 'لسان الدين بن الخطيب' THEN 'Lisan al-Din ibn al-Khatib'
  WHEN 'ابن خفاجة' THEN 'Ibn Khafaja'
  WHEN 'أبو الفرج الأصفهاني' THEN 'Abu al-Faraj al-Isfahani'
  WHEN 'ابن هانئ الأندلسي' THEN 'Ibn Hani al-Andalusi'
  WHEN 'ابن دريد' THEN 'Ibn Duraid'
  WHEN 'أبو العلاء المعري' THEN 'Al-Ma''arri'
  WHEN 'الثعالبي' THEN 'Al-Tha''alibi'
  WHEN 'الطغرائي' THEN 'Al-Tughra''i'
  WHEN 'ابن نباتة المصري' THEN 'Ibn Nubata al-Misri'
  WHEN 'البوصيري' THEN 'Al-Busiri'
  WHEN 'الإمام الشافعي' THEN 'Imam al-Shafi''i'
  WHEN 'علي بن أبي طالب' THEN 'Ali ibn Abi Talib'
  WHEN 'الصمة القشيري' THEN 'Al-Samma al-Qushayri'
  WHEN 'عروة بن الورد' THEN 'Urwa ibn al-Ward'
  WHEN 'الحطيئة' THEN 'Al-Hutay''a'
  WHEN 'جميل بثينة' THEN 'Jamil Buthayna'
  WHEN 'قيس بن الملوح' THEN 'Qays ibn al-Mulawwah'
  WHEN 'مجنون ليلى' THEN 'Majnun Layla'
  WHEN 'عمر بن أبي ربيعة' THEN 'Umar ibn Abi Rabi''a'
  WHEN 'الفرزدق' THEN 'Al-Farazdaq'
  WHEN 'ذو القرنين' THEN 'Dhu al-Qarnayn'
  WHEN 'السموأل' THEN 'Al-Samaw''al'
  WHEN 'الأحنف بن قيس' THEN 'Al-Ahnaf ibn Qays'
  -- Modern/contemporary poets
  WHEN 'عبد المعطي حجازي' THEN 'Ahmad Abd al-Mu''ti Hijazi'
  WHEN 'سعدي يوسف' THEN 'Saadi Youssef'
  WHEN 'محمد مهدي الجواهري' THEN 'Muhammad Mahdi al-Jawahiri'
  WHEN 'أحمد فؤاد نجم' THEN 'Ahmad Fuad Negm'
  WHEN 'عبد الرحمن شكري' THEN 'Abd al-Rahman Shukri'
  WHEN 'خليل مطران' THEN 'Khalil Mutran'
  WHEN 'إبراهيم طوقان' THEN 'Ibrahim Tuqan'
  WHEN 'أبو ريشة' THEN 'Abu Risha'
  WHEN 'محمد إقبال' THEN 'Muhammad Iqbal'
  WHEN 'بابلو نيرودا' THEN 'Pablo Neruda'
  WHEN 'طاهر بن جلون' THEN 'Tahar Ben Jelloun'
  WHEN 'يوسف الخال' THEN 'Yusuf al-Khal'
  WHEN 'أنسي الحاج' THEN 'Unsi al-Hajj'
  WHEN 'شوقي بزيع' THEN 'Shawqi Bazigh'
  WHEN 'عباس بن الأحنف' THEN 'Abbas ibn al-Ahnaf'
  WHEN 'ابن الأبار' THEN 'Ibn al-Abbar'
  WHEN 'الوليد بن يزيد' THEN 'Al-Walid ibn Yazid'
  WHEN 'عبيد بن الأبرص' THEN 'Ubayd ibn al-Abras'
  WHEN 'سلمى الجيوسي' THEN 'Salma Khadra Jayyusi'
END
WHERE name_en IS NULL;

-- Flag any poets still without English names (for monitoring)
-- SELECT name FROM public.poets WHERE name_en IS NULL;

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_poets_name_en ON public.poets (name_en) WHERE name_en IS NOT NULL;

-- Add English title column to poems table for bilingual display
ALTER TABLE public.poems ADD COLUMN IF NOT EXISTS title_en TEXT;
